/**
 * Seed Script: Fortune Global 500 Companies
 * 
 * Inserts all Fortune Global 500 companies (2024 list) into the Prism Connex CRM database.
 * Each company includes: name, category, description, domain, website, founded year,
 * employee range, headquarters, region, revenue range, engagement score, trust signals,
 * tags, and more.
 * 
 * Usage: npx tsx prisma/seed-fortune500.ts
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient({ log: ["error"] });

interface Fortune500Company {
  name: string;
  category: string;
  description: string;
  domain: string;
  website: string;
  founded: string;
  employeeRange: string;
  headquarters: string;
  region: string;
  revenueRange: string;
  engagementScore: number;
  trustSignals: string;
  tags: string;
  email: string;
  phone: string;
  highlights: string;
  insights: string;
}

// Fortune Global 500 - 2024 List (ranked by revenue)
const fortune500Companies: Fortune500Company[] = [
  { name: "Walmart", category: "retail", description: "Walmart Inc. is the world's largest company by revenue, operating a chain of hypermarkets, discount department stores, and grocery stores.", domain: "walmart.com", website: "https://www.walmart.com", founded: "1962", employeeRange: "10,001+", headquarters: "Bentonville, AR, USA", region: "North America", revenueRange: "$500B+", engagementScore: 98, trustSignals: "Fortune Global 500 #1, S&P 500", tags: "Retail, E-Commerce, Grocery, Supply Chain", email: "corporate@walmart.com", phone: "+1-479-273-4000", highlights: "World's largest retailer, 2.1M+ employees globally", insights: "Expanding e-commerce and last-mile delivery capabilities" },
  { name: "Amazon", category: "technology", description: "Amazon.com, Inc. is a multinational technology company focusing on e-commerce, cloud computing (AWS), digital streaming, and artificial intelligence.", domain: "amazon.com", website: "https://www.amazon.com", founded: "1994", employeeRange: "10,001+", headquarters: "Seattle, WA, USA", region: "North America", revenueRange: "$500B+", engagementScore: 97, trustSignals: "Fortune Global 500 #2, FAANG", tags: "Technology, E-Commerce, Cloud Computing, AWS, AI", email: "ir@amazon.com", phone: "+1-206-266-1000", highlights: "AWS market leader, Prime ecosystem, AI/ML pioneer", insights: "Investing heavily in generative AI and satellite internet" },
  { name: "State Grid Corporation of China", category: "energy & utilities", description: "State Grid Corporation of China is the world's largest utility company, operating the largest electric utility grid in the world.", domain: "sgcc.com.cn", website: "http://www.sgcc.com.cn", founded: "2002", employeeRange: "10,001+", headquarters: "Beijing, China", region: "Asia-Pacific", revenueRange: "$500B+", engagementScore: 85, trustSignals: "Fortune Global 500 #3, State-owned", tags: "Energy, Utilities, Power Grid, Infrastructure", email: "info@sgcc.com.cn", phone: "+86-10-66597114", highlights: "World's largest utility, serves 1.1B+ people", insights: "Investing in ultra-high voltage transmission and smart grids" },
  { name: "Saudi Aramco", category: "energy & utilities", description: "Saudi Arabian Oil Company (Aramco) is a petroleum and natural gas company, the world's largest oil producer.", domain: "aramco.com", website: "https://www.aramco.com", founded: "1933", employeeRange: "10,001+", headquarters: "Dhahran, Saudi Arabia", region: "Middle East", revenueRange: "$500B+", engagementScore: 90, trustSignals: "Fortune Global 500 #4, World's most profitable company", tags: "Oil & Gas, Energy, Petroleum, Chemicals", email: "media.inquiries@aramco.com", phone: "+966-13-880-1414", highlights: "World's largest oil producer and most profitable company", insights: "Diversifying into hydrogen, renewables, and downstream chemicals" },
  { name: "China National Petroleum Corporation", category: "energy & utilities", description: "China National Petroleum Corporation (CNPC) is one of the largest integrated energy groups in the world.", domain: "cnpc.com.cn", website: "http://www.cnpc.com.cn", founded: "1988", employeeRange: "10,001+", headquarters: "Beijing, China", region: "Asia-Pacific", revenueRange: "$400B+", engagementScore: 82, trustSignals: "Fortune Global 500 #5, State-owned", tags: "Oil & Gas, Energy, Petroleum, Natural Gas", email: "service@cnpc.com.cn", phone: "+86-10-59982114", highlights: "China's largest oil and gas producer, 1.3M+ employees", insights: "Expanding natural gas production and green energy investments" },
  { name: "Sinopec Group", category: "energy & utilities", description: "China Petrochemical Corporation (Sinopec Group) is one of the world's largest integrated energy and chemical companies.", domain: "sinopecgroup.com", website: "http://www.sinopecgroup.com", founded: "1998", employeeRange: "10,001+", headquarters: "Beijing, China", region: "Asia-Pacific", revenueRange: "$400B+", engagementScore: 81, trustSignals: "Fortune Global 500 #6, State-owned", tags: "Oil & Gas, Energy, Chemicals, Refining", email: "ir@sinopec.com", phone: "+86-10-59960114", highlights: "World's largest oil refiner by capacity", insights: "Investing in hydrogen energy and biofuels" },
  { name: "Apple", category: "technology", description: "Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide.", domain: "apple.com", website: "https://www.apple.com", founded: "1976", employeeRange: "10,001+", headquarters: "Cupertino, CA, USA", region: "North America", revenueRange: "$300B+", engagementScore: 99, trustSignals: "Fortune Global 500 #7, World's most valuable company", tags: "Technology, Consumer Electronics, Software, Services", email: "investor_relations@apple.com", phone: "+1-408-996-1010", highlights: "Most valuable company globally, ecosystem of devices and services", insights: "Entering spatial computing with Vision Pro, expanding services revenue" },
  { name: "UnitedHealth Group", category: "healthcare", description: "UnitedHealth Group Incorporated is a healthcare company offering health care coverage and benefits through UnitedHealthcare and Optum.", domain: "unitedhealthgroup.com", website: "https://www.unitedhealthgroup.com", founded: "1977", employeeRange: "10,001+", headquarters: "Minnetonka, MN, USA", region: "North America", revenueRange: "$300B+", engagementScore: 88, trustSignals: "Fortune Global 500 #8, Dow 30", tags: "Healthcare, Insurance, Health Services, Technology", email: "investor_relations@uhg.com", phone: "+1-952-936-1300", highlights: "Largest health insurer in the US, Optum health services", insights: "Integrating AI and data analytics into care delivery" },
  { name: "Berkshire Hathaway", category: "financial services", description: "Berkshire Hathaway Inc. is a multinational conglomerate holding company led by Warren Buffett, with diverse business interests.", domain: "berkshirehathaway.com", website: "https://www.berkshirehathaway.com", founded: "1839", employeeRange: "10,001+", headquarters: "Omaha, NE, USA", region: "North America", revenueRange: "$300B+", engagementScore: 92, trustSignals: "Fortune Global 500 #9, Warren Buffett", tags: "Conglomerate, Insurance, Finance, Investments", email: "berkshire@berkshirehathaway.com", phone: "+1-402-346-1400", highlights: "One of the world's largest conglomerates, diversified portfolio", insights: "Significant holdings in Apple, energy, and insurance sectors" },
  { name: "CVS Health", category: "healthcare", description: "CVS Health Corporation is the largest healthcare company in the US, providing health services through pharmacies, insurance (Aetna), and clinics.", domain: "cvshealth.com", website: "https://www.cvshealth.com", founded: "1963", employeeRange: "10,001+", headquarters: "Woonsocket, RI, USA", region: "North America", revenueRange: "$300B+", engagementScore: 84, trustSignals: "Fortune Global 500 #10, S&P 500", tags: "Healthcare, Pharmacy, Insurance, Retail Health", email: "investors@cvshealth.com", phone: "+1-401-765-1500", highlights: "Largest pharmacy chain in US, integrated health services", insights: "Expanding MinuteClinic and virtual care capabilities" },
  { name: "ExxonMobil", category: "energy & utilities", description: "Exxon Mobil Corporation is one of the world's largest publicly traded energy providers and chemical manufacturers.", domain: "exxonmobil.com", website: "https://corporate.exxonmobil.com", founded: "1999", employeeRange: "10,001+", headquarters: "Spring, TX, USA", region: "North America", revenueRange: "$300B+", engagementScore: 86, trustSignals: "Fortune Global 500, Dow 30", tags: "Oil & Gas, Energy, Chemicals, Refining", email: "investors@exxonmobil.com", phone: "+1-972-940-6000", highlights: "One of the world's largest integrated oil companies", insights: "Investing in carbon capture and low-emission technologies" },
  { name: "Alphabet (Google)", category: "technology", description: "Alphabet Inc. is a multinational conglomerate and parent company of Google, specializing in internet services, advertising, cloud computing, and AI.", domain: "google.com", website: "https://abc.xyz", founded: "2015", employeeRange: "10,001+", headquarters: "Mountain View, CA, USA", region: "North America", revenueRange: "$300B+", engagementScore: 96, trustSignals: "Fortune Global 500, FAANG", tags: "Technology, Advertising, Cloud Computing, AI, Search", email: "investor-relations@abc.xyz", phone: "+1-650-253-0000", highlights: "Dominant in search, YouTube, Android, and cloud", insights: "Leading generative AI race with Gemini, expanding cloud revenue" },
  { name: "Samsung Electronics", category: "technology", description: "Samsung Electronics Co., Ltd. is a global leader in technology, manufacturing semiconductors, consumer electronics, and mobile devices.", domain: "samsung.com", website: "https://www.samsung.com", founded: "1969", employeeRange: "10,001+", headquarters: "Suwon, South Korea", region: "Asia-Pacific", revenueRange: "$200B+", engagementScore: 91, trustSignals: "Fortune Global 500, Global brand", tags: "Technology, Semiconductors, Consumer Electronics, Mobile", email: "ir@samsung.com", phone: "+82-2-2255-0114", highlights: "World's largest semiconductor and smartphone manufacturer", insights: "Investing in advanced chip manufacturing and AI integration" },
  { name: "McKesson", category: "healthcare", description: "McKesson Corporation delivers pharmaceuticals, medical supplies, and healthcare IT solutions globally.", domain: "mckesson.com", website: "https://www.mckesson.com", founded: "1833", employeeRange: "10,001+", headquarters: "Irving, TX, USA", region: "North America", revenueRange: "$200B+", engagementScore: 80, trustSignals: "Fortune Global 500, S&P 500", tags: "Healthcare, Pharmaceuticals, Distribution, IT Solutions", email: "investors@mckesson.com", phone: "+1-972-446-4800", highlights: "Largest pharmaceutical distributor in North America", insights: "Expanding oncology and specialty pharmacy networks" },
  { name: "Toyota Motor", category: "automotive", description: "Toyota Motor Corporation is the world's largest automaker by volume, known for hybrid technology and manufacturing excellence.", domain: "toyota.com", website: "https://www.toyota.com", founded: "1937", employeeRange: "10,001+", headquarters: "Toyota City, Japan", region: "Asia-Pacific", revenueRange: "$200B+", engagementScore: 89, trustSignals: "Fortune Global 500, World's largest automaker", tags: "Automotive, Hybrid Vehicles, Manufacturing, Mobility", email: "ir@toyota.co.jp", phone: "+81-565-28-2121", highlights: "Pioneer in hybrid technology, largest automaker globally", insights: "Expanding BEV lineup while maintaining hybrid leadership" },
  { name: "Volkswagen Group", category: "automotive", description: "Volkswagen AG is a German multinational automotive manufacturer, one of the world's largest automakers by revenue.", domain: "volkswagen.com", website: "https://www.volkswagen.com", founded: "1937", employeeRange: "10,001+", headquarters: "Wolfsburg, Germany", region: "Europe", revenueRange: "$200B+", engagementScore: 87, trustSignals: "Fortune Global 500, Major automaker", tags: "Automotive, Electric Vehicles, Manufacturing", email: "investor.relations@volkswagen.de", phone: "+49-5361-9-0", highlights: "Multi-brand portfolio: VW, Audi, Porsche, Lamborghini", insights: "Massive investment in EV platform and software defined vehicles" },
  { name: "Shell", category: "energy & utilities", description: "Shell plc is a British multinational oil and gas company, one of the oil and gas supermajors.", domain: "shell.com", website: "https://www.shell.com", founded: "1907", employeeRange: "10,001+", headquarters: "London, UK", region: "Europe", revenueRange: "$200B+", engagementScore: 85, trustSignals: "Fortune Global 500, Oil supermajor", tags: "Oil & Gas, Energy, LNG, Renewables", email: "ir@shell.com", phone: "+44-20-7934-1234", highlights: "World's largest LNG trader, diversified energy company", insights: "Transitioning to lower-carbon energy while maintaining oil production" },
  { name: "TotalEnergies", category: "energy & utilities", description: "TotalEnergies SE is a French multinational integrated energy and petroleum company.", domain: "totalenergies.com", website: "https://www.totalenergies.com", founded: "1924", employeeRange: "10,001+", headquarters: "Courbevoie, France", region: "Europe", revenueRange: "$200B+", engagementScore: 83, trustSignals: "Fortune Global 500, Energy supermajor", tags: "Oil & Gas, Energy, Renewables, LNG", email: "ir@totalenergies.com", phone: "+33-1-47-44-45-46", highlights: "Leading integrated energy company with strong renewables push", insights: "Largest renewable energy capacity among oil majors" },
  { name: "Chevron", category: "energy & utilities", description: "Chevron Corporation is one of the world's leading integrated energy companies.", domain: "chevron.com", website: "https://www.chevron.com", founded: "1879", employeeRange: "10,001+", headquarters: "San Ramon, CA, USA", region: "North America", revenueRange: "$200B+", engagementScore: 84, trustSignals: "Fortune Global 500, Dow 30", tags: "Oil & Gas, Energy, Chemicals", email: "ir@chevron.com", phone: "+1-925-842-1000", highlights: "Major integrated energy company with global operations", insights: "Acquiring Hess Corporation to expand production portfolio" },
  { name: "BP", category: "energy & utilities", description: "BP plc is a British multinational oil and gas company, one of the world's seven oil and gas supermajors.", domain: "bp.com", website: "https://www.bp.com", founded: "1909", employeeRange: "10,001+", headquarters: "London, UK", region: "Europe", revenueRange: "$200B+", engagementScore: 82, trustSignals: "Fortune Global 500, Oil supermajor", tags: "Oil & Gas, Energy, Renewables, EV Charging", email: "bppress@bp.com", phone: "+44-20-7496-4000", highlights: "Global energy company with growing renewables portfolio", insights: "Expanding EV charging infrastructure and bioenergy production" },
  { name: "Costco Wholesale", category: "retail", description: "Costco Wholesale Corporation operates an international chain of membership warehouses.", domain: "costco.com", website: "https://www.costco.com", founded: "1983", employeeRange: "10,001+", headquarters: "Issaquah, WA, USA", region: "North America", revenueRange: "$200B+", engagementScore: 87, trustSignals: "Fortune Global 500, S&P 500", tags: "Retail, Wholesale, Membership, E-Commerce", email: "investor@costco.com", phone: "+1-425-313-8100", highlights: "Third-largest retailer globally, membership model", insights: "Expanding international presence and e-commerce capabilities" },
  { name: "Microsoft", category: "technology", description: "Microsoft Corporation develops, licenses, and supports software products, services, and devices worldwide.", domain: "microsoft.com", website: "https://www.microsoft.com", founded: "1975", employeeRange: "10,001+", headquarters: "Redmond, WA, USA", region: "North America", revenueRange: "$200B+", engagementScore: 98, trustSignals: "Fortune Global 500, FAANG+, World's most valuable", tags: "Technology, Cloud Computing, Software, AI, Gaming", email: "msft@microsoft.com", phone: "+1-425-882-8080", highlights: "Azure cloud leader, Office 365, Windows, Copilot AI", insights: "Leading enterprise AI adoption with OpenAI partnership" },
  { name: "AmerisourceBergen (Cencora)", category: "healthcare", description: "Cencora (formerly AmerisourceBergen) is a pharmaceutical sourcing and distribution services company.", domain: "cencora.com", website: "https://www.cencora.com", founded: "2001", employeeRange: "10,001+", headquarters: "Conshohocken, PA, USA", region: "North America", revenueRange: "$200B+", engagementScore: 78, trustSignals: "Fortune Global 500, S&P 500", tags: "Healthcare, Pharmaceuticals, Distribution", email: "investors@cencora.com", phone: "+1-610-727-7000", highlights: "One of the Big Three US pharmaceutical distributors", insights: "Expanding specialty pharmacy and cell/gene therapy logistics" },
  { name: "China State Construction Engineering", category: "construction", description: "China State Construction Engineering Corporation is the world's largest construction company.", domain: "cscec.com", website: "http://www.cscec.com", founded: "1982", employeeRange: "10,001+", headquarters: "Beijing, China", region: "Asia-Pacific", revenueRange: "$200B+", engagementScore: 76, trustSignals: "Fortune Global 500, State-owned", tags: "Construction, Engineering, Real Estate, Infrastructure", email: "info@cscec.com", phone: "+86-10-86498888", highlights: "World's largest construction company by revenue", insights: "Expanding international infrastructure projects" },
  { name: "Marathon Petroleum", category: "energy & utilities", description: "Marathon Petroleum Corporation is an integrated downstream energy company in the US.", domain: "marathonpetroleum.com", website: "https://www.marathonpetroleum.com", founded: "2011", employeeRange: "10,001+", headquarters: "Findlay, OH, USA", region: "North America", revenueRange: "$100B+", engagementScore: 77, trustSignals: "Fortune Global 500, S&P 500", tags: "Oil & Gas, Refining, Energy, Marketing", email: "investor_relations@marathonpetroleum.com", phone: "+1-419-422-2121", highlights: "Largest petroleum refiner in the US", insights: "Expanding renewable fuel production capacity" },
  { name: "Glencore", category: "mining & metals", description: "Glencore plc is a Swiss multinational commodity trading and mining company.", domain: "glencore.com", website: "https://www.glencore.com", founded: "1974", employeeRange: "10,001+", headquarters: "Baar, Switzerland", region: "Europe", revenueRange: "$200B+", engagementScore: 79, trustSignals: "Fortune Global 500, Commodity giant", tags: "Mining, Commodities, Trading, Metals, Energy", email: "info@glencore.com", phone: "+41-41-709-2000", highlights: "World's largest commodity trader", insights: "Expanding recycling operations and critical minerals supply" },
  { name: "Trafigura", category: "energy & utilities", description: "Trafigura Group Pte Ltd is one of the world's largest independent commodity trading companies.", domain: "trafigura.com", website: "https://www.trafigura.com", founded: "1993", employeeRange: "5,001-10,000", headquarters: "Singapore", region: "Asia-Pacific", revenueRange: "$200B+", engagementScore: 75, trustSignals: "Fortune Global 500, Commodity trader", tags: "Commodities, Trading, Oil & Gas, Metals", email: "enquiries@trafigura.com", phone: "+65-6319-2960", highlights: "Second-largest independent oil trader globally", insights: "Expanding metals and minerals trading operations" },
  { name: "Vitol", category: "energy & utilities", description: "Vitol Group is a Dutch energy and commodities trading company, the world's largest independent energy trader.", domain: "vitol.com", website: "https://www.vitol.com", founded: "1966", employeeRange: "1,001-5,000", headquarters: "Geneva, Switzerland", region: "Europe", revenueRange: "$200B+", engagementScore: 74, trustSignals: "Fortune Global 500, Largest energy trader", tags: "Energy, Trading, Oil & Gas, Commodities", email: "info@vitol.com", phone: "+41-22-595-1000", highlights: "World's largest independent energy trader", insights: "Investing in renewable energy and carbon markets" },
  { name: "Foxconn (Hon Hai)", category: "technology", description: "Hon Hai Precision Industry Co., Ltd. (Foxconn) is the world's largest electronics manufacturer.", domain: "foxconn.com", website: "https://www.foxconn.com", founded: "1974", employeeRange: "10,001+", headquarters: "Taipei, Taiwan", region: "Asia-Pacific", revenueRange: "$200B+", engagementScore: 80, trustSignals: "Fortune Global 500, Apple supplier", tags: "Manufacturing, Electronics, Technology, EV", email: "ir@foxconn.com", phone: "+886-2-2268-3466", highlights: "World's largest contract electronics manufacturer", insights: "Diversifying into EV manufacturing and AI servers" },
  { name: "Meta Platforms", category: "technology", description: "Meta Platforms, Inc. (formerly Facebook) builds technologies for social media, messaging, virtual and augmented reality.", domain: "meta.com", website: "https://about.meta.com", founded: "2004", employeeRange: "10,001+", headquarters: "Menlo Park, CA, USA", region: "North America", revenueRange: "$100B+", engagementScore: 95, trustSignals: "Fortune Global 500, FAANG", tags: "Technology, Social Media, VR/AR, Advertising, AI", email: "ir@meta.com", phone: "+1-650-543-4800", highlights: "3B+ users across Facebook, Instagram, WhatsApp", insights: "Massive investment in AI, metaverse, and Reality Labs" },
  { name: "JPMorgan Chase", category: "financial services", description: "JPMorgan Chase & Co. is the largest bank in the United States and one of the world's most prominent financial institutions.", domain: "jpmorganchase.com", website: "https://www.jpmorganchase.com", founded: "2000", employeeRange: "10,001+", headquarters: "New York, NY, USA", region: "North America", revenueRange: "$100B+", engagementScore: 93, trustSignals: "Fortune Global 500, Dow 30, Largest US bank", tags: "Banking, Finance, Investment Banking, Asset Management", email: "investor.relations@jpmchase.com", phone: "+1-212-270-6000", highlights: "Largest US bank by assets, global investment banking leader", insights: "Leading digital banking innovation and blockchain adoption" },
  { name: "Johnson & Johnson", category: "healthcare", description: "Johnson & Johnson is a multinational corporation that develops medical devices, pharmaceutical, and consumer packaged goods.", domain: "jnj.com", website: "https://www.jnj.com", founded: "1886", employeeRange: "10,001+", headquarters: "New Brunswick, NJ, USA", region: "North America", revenueRange: "$80B+", engagementScore: 90, trustSignals: "Fortune Global 500, Dow 30, S&P 500", tags: "Healthcare, Pharmaceuticals, Medical Devices, Consumer Health", email: "investor-relations@its.jnj.com", phone: "+1-732-524-0400", highlights: "Global healthcare leader, diversified portfolio", insights: "Separated consumer health division as Kenvue" },
  { name: "Tesla", category: "automotive", description: "Tesla, Inc. designs, develops, manufactures, and sells electric vehicles, energy generation and storage systems.", domain: "tesla.com", website: "https://www.tesla.com", founded: "2003", employeeRange: "10,001+", headquarters: "Austin, TX, USA", region: "North America", revenueRange: "$80B+", engagementScore: 97, trustSignals: "Fortune Global 500, S&P 500, EV pioneer", tags: "Automotive, Electric Vehicles, Energy, AI, Robotics", email: "ir@tesla.com", phone: "+1-512-516-8177", highlights: "World's most valuable automaker, leader in EVs", insights: "Expanding into autonomous driving, robotics, and energy storage" },
  { name: "Procter & Gamble", category: "consumer goods", description: "The Procter & Gamble Company provides branded consumer packaged goods worldwide.", domain: "pg.com", website: "https://www.pg.com", founded: "1837", employeeRange: "10,001+", headquarters: "Cincinnati, OH, USA", region: "North America", revenueRange: "$80B+", engagementScore: 88, trustSignals: "Fortune Global 500, Dow 30", tags: "Consumer Goods, FMCG, Personal Care, Home Care", email: "investors@pg.com", phone: "+1-513-983-1100", highlights: "65+ billion-dollar brands including Tide, Pampers, Gillette", insights: "Leading digital transformation in consumer goods marketing" },
  { name: "Nestlé", category: "consumer goods", description: "Nestlé S.A. is the world's largest food and beverage company.", domain: "nestle.com", website: "https://www.nestle.com", founded: "1866", employeeRange: "10,001+", headquarters: "Vevey, Switzerland", region: "Europe", revenueRange: "$90B+", engagementScore: 87, trustSignals: "Fortune Global 500, World's largest food company", tags: "Food & Beverage, Consumer Goods, Nutrition, Health", email: "ir@nestle.com", phone: "+41-21-924-2111", highlights: "World's largest food company, 2000+ brands globally", insights: "Focusing on health-science nutrition and plant-based products" },
  { name: "Coca-Cola", category: "consumer goods", description: "The Coca-Cola Company is the world's largest beverage company, offering over 500 brands globally.", domain: "coca-colacompany.com", website: "https://www.coca-colacompany.com", founded: "1886", employeeRange: "10,001+", headquarters: "Atlanta, GA, USA", region: "North America", revenueRange: "$40B+", engagementScore: 91, trustSignals: "Fortune Global 500, Dow 30, Iconic brand", tags: "Beverages, Consumer Goods, Marketing, Distribution", email: "investors@coca-cola.com", phone: "+1-404-676-2121", highlights: "World's most recognized brand, 200+ countries", insights: "Expanding zero-sugar portfolio and digital vending" },
  { name: "PepsiCo", category: "consumer goods", description: "PepsiCo, Inc. is a multinational food, snack, and beverage corporation.", domain: "pepsico.com", website: "https://www.pepsico.com", founded: "1965", employeeRange: "10,001+", headquarters: "Purchase, NY, USA", region: "North America", revenueRange: "$80B+", engagementScore: 88, trustSignals: "Fortune Global 500, Dow 30", tags: "Food & Beverage, Snacks, Consumer Goods", email: "investor@pepsico.com", phone: "+1-914-253-2000", highlights: "22 billion-dollar brands including Pepsi, Lay's, Gatorade", insights: "Growing healthier snacks and sustainable packaging" },
  { name: "Netflix", category: "technology", description: "Netflix, Inc. is the world's leading entertainment streaming service with 250M+ subscribers.", domain: "netflix.com", website: "https://www.netflix.com", founded: "1997", employeeRange: "10,001+", headquarters: "Los Gatos, CA, USA", region: "North America", revenueRange: "$30B+", engagementScore: 94, trustSignals: "Fortune Global 500, S&P 500, FAANG", tags: "Technology, Entertainment, Streaming, Content", email: "ir@netflix.com", phone: "+1-408-540-3700", highlights: "World's leading streaming service, 250M+ paid subscribers", insights: "Expanding ad-supported tier and live sports content" },
  { name: "NVIDIA", category: "technology", description: "NVIDIA Corporation designs GPUs and AI computing platforms for gaming, professional visualization, data center, and automotive markets.", domain: "nvidia.com", website: "https://www.nvidia.com", founded: "1993", employeeRange: "10,001+", headquarters: "Santa Clara, CA, USA", region: "North America", revenueRange: "$60B+", engagementScore: 99, trustSignals: "Fortune Global 500, S&P 500, AI chip leader", tags: "Technology, Semiconductors, AI, GPU, Data Center", email: "investor.relations@nvidia.com", phone: "+1-408-486-2000", highlights: "Dominant AI chip maker, powering AI revolution", insights: "Leading the AI infrastructure buildout with data center GPUs" },
  { name: "Intel", category: "technology", description: "Intel Corporation designs, manufactures, and sells computer components and related products worldwide.", domain: "intel.com", website: "https://www.intel.com", founded: "1968", employeeRange: "10,001+", headquarters: "Santa Clara, CA, USA", region: "North America", revenueRange: "$50B+", engagementScore: 85, trustSignals: "Fortune Global 500, Dow 30", tags: "Technology, Semiconductors, Manufacturing, AI", email: "investor.relations@intel.com", phone: "+1-408-765-8080", highlights: "World's largest semiconductor chip maker by revenue", insights: "Investing $100B+ in US chip manufacturing expansion" },
  { name: "IBM", category: "technology", description: "International Business Machines Corporation provides integrated solutions and services worldwide.", domain: "ibm.com", website: "https://www.ibm.com", founded: "1911", employeeRange: "10,001+", headquarters: "Armonk, NY, USA", region: "North America", revenueRange: "$60B+", engagementScore: 86, trustSignals: "Fortune Global 500, Dow 30, Enterprise IT leader", tags: "Technology, Cloud Computing, AI, Consulting, Enterprise", email: "ibm_investor@ibm.com", phone: "+1-914-499-1900", highlights: "Enterprise AI and hybrid cloud leader, Red Hat", insights: "Pivoting to AI and hybrid cloud with watsonx platform" },
  { name: "Siemens", category: "technology", description: "Siemens AG is a global technology powerhouse focused on industry, infrastructure, transport, and healthcare.", domain: "siemens.com", website: "https://www.siemens.com", founded: "1847", employeeRange: "10,001+", headquarters: "Munich, Germany", region: "Europe", revenueRange: "$80B+", engagementScore: 86, trustSignals: "Fortune Global 500, DAX 30", tags: "Technology, Industrial, Manufacturing, Healthcare, Energy", email: "investor.relations@siemens.com", phone: "+49-89-636-00", highlights: "Global industrial technology leader, digital twin pioneer", insights: "Leading industrial digitalization and smart infrastructure" },
  { name: "Sony Group", category: "technology", description: "Sony Group Corporation is a global conglomerate in electronics, gaming, entertainment, and financial services.", domain: "sony.com", website: "https://www.sony.com", founded: "1946", employeeRange: "10,001+", headquarters: "Tokyo, Japan", region: "Asia-Pacific", revenueRange: "$80B+", engagementScore: 88, trustSignals: "Fortune Global 500, PlayStation maker", tags: "Technology, Entertainment, Gaming, Electronics, Music", email: "ir@sony.com", phone: "+81-3-6748-2111", highlights: "PlayStation ecosystem, music, movies, and image sensors", insights: "Expanding gaming and entertainment IP across platforms" },
  { name: "Visa", category: "financial services", description: "Visa Inc. is a global payments technology company connecting consumers, businesses, financial institutions, and governments.", domain: "visa.com", website: "https://www.visa.com", founded: "1958", employeeRange: "10,001+", headquarters: "San Francisco, CA, USA", region: "North America", revenueRange: "$30B+", engagementScore: 92, trustSignals: "Fortune Global 500, Dow 30, Payment leader", tags: "Financial Services, Payments, Fintech, Technology", email: "investorrelations@visa.com", phone: "+1-650-432-3200", highlights: "World's largest payment network, processes $12T+ annually", insights: "Expanding into B2B payments, crypto, and real-time payments" },
  { name: "Mastercard", category: "financial services", description: "Mastercard Incorporated is a global technology company in the payments industry.", domain: "mastercard.com", website: "https://www.mastercard.com", founded: "1966", employeeRange: "10,001+", headquarters: "Purchase, NY, USA", region: "North America", revenueRange: "$25B+", engagementScore: 90, trustSignals: "Fortune Global 500, S&P 500", tags: "Financial Services, Payments, Fintech, Technology", email: "investor.relations@mastercard.com", phone: "+1-914-249-2000", highlights: "Second-largest payment processing network globally", insights: "Investing in open banking and blockchain-based payments" },
  { name: "Walt Disney", category: "entertainment", description: "The Walt Disney Company is a diversified worldwide entertainment company.", domain: "disney.com", website: "https://www.thewaltdisneycompany.com", founded: "1923", employeeRange: "10,001+", headquarters: "Burbank, CA, USA", region: "North America", revenueRange: "$80B+", engagementScore: 91, trustSignals: "Fortune Global 500, Dow 30, Iconic brand", tags: "Entertainment, Media, Streaming, Theme Parks", email: "investor.relations@disney.com", phone: "+1-818-560-1000", highlights: "Disney+, Marvel, Star Wars, theme parks ecosystem", insights: "Streaming profitability focus and sports rights expansion" },
  { name: "Nike", category: "consumer goods", description: "NIKE, Inc. is the world's largest supplier of athletic shoes and apparel.", domain: "nike.com", website: "https://www.nike.com", founded: "1964", employeeRange: "10,001+", headquarters: "Beaverton, OR, USA", region: "North America", revenueRange: "$50B+", engagementScore: 90, trustSignals: "Fortune Global 500, Dow 30, Iconic brand", tags: "Consumer Goods, Sportswear, Footwear, Apparel", email: "investors@nike.com", phone: "+1-503-671-6453", highlights: "World's largest athletic brand, DTC transformation", insights: "Rebuilding wholesale partnerships and digital-first strategy" },
  { name: "Pfizer", category: "healthcare", description: "Pfizer Inc. discovers, develops, manufactures, and markets biopharmaceutical products worldwide.", domain: "pfizer.com", website: "https://www.pfizer.com", founded: "1849", employeeRange: "10,001+", headquarters: "New York, NY, USA", region: "North America", revenueRange: "$50B+", engagementScore: 89, trustSignals: "Fortune Global 500, S&P 500, Dow 30", tags: "Healthcare, Pharmaceuticals, Biotech, Vaccines", email: "pfizer_investor@pfizer.com", phone: "+1-212-733-2323", highlights: "Major pharma company, COVID vaccine maker", insights: "Expanding oncology and rare disease pipeline" },
  { name: "Roche", category: "healthcare", description: "Roche Holding AG is a Swiss multinational healthcare company operating in pharmaceuticals and diagnostics.", domain: "roche.com", website: "https://www.roche.com", founded: "1896", employeeRange: "10,001+", headquarters: "Basel, Switzerland", region: "Europe", revenueRange: "$60B+", engagementScore: 87, trustSignals: "Fortune Global 500, Global pharma leader", tags: "Healthcare, Pharmaceuticals, Diagnostics, Biotech", email: "investor.relations@roche.com", phone: "+41-61-688-1111", highlights: "World's largest biotech company, cancer treatment leader", insights: "Leading personalized medicine and diagnostics integration" },
  { name: "Novartis", category: "healthcare", description: "Novartis AG is a Swiss multinational pharmaceutical corporation.", domain: "novartis.com", website: "https://www.novartis.com", founded: "1996", employeeRange: "10,001+", headquarters: "Basel, Switzerland", region: "Europe", revenueRange: "$40B+", engagementScore: 85, trustSignals: "Fortune Global 500, Global pharma", tags: "Healthcare, Pharmaceuticals, Biotech", email: "investor.relations@novartis.com", phone: "+41-61-324-1111", highlights: "Focused innovative medicines company", insights: "Streamlined to pure-play innovative medicines after Sandoz spinoff" },
  { name: "AstraZeneca", category: "healthcare", description: "AstraZeneca PLC is a British-Swedish multinational pharmaceutical and biotechnology company.", domain: "astrazeneca.com", website: "https://www.astrazeneca.com", founded: "1999", employeeRange: "10,001+", headquarters: "Cambridge, UK", region: "Europe", revenueRange: "$40B+", engagementScore: 86, trustSignals: "Fortune Global 500, FTSE 100", tags: "Healthcare, Pharmaceuticals, Biotech, Oncology", email: "ir@astrazeneca.com", phone: "+44-20-3749-5000", highlights: "Leading oncology and biopharmaceutical company", insights: "Strong oncology pipeline driving growth" },
  { name: "Abbott Laboratories", category: "healthcare", description: "Abbott Laboratories is a global healthcare company creating breakthrough products in diagnostics, medical devices, nutrition, and pharmaceuticals.", domain: "abbott.com", website: "https://www.abbott.com", founded: "1888", employeeRange: "10,001+", headquarters: "Abbott Park, IL, USA", region: "North America", revenueRange: "$40B+", engagementScore: 84, trustSignals: "Fortune Global 500, S&P 500", tags: "Healthcare, Medical Devices, Diagnostics, Nutrition", email: "investor.relations@abbott.com", phone: "+1-224-667-6100", highlights: "Diversified healthcare, FreeStyle Libre diabetes technology", insights: "Continuous glucose monitoring driving medical device growth" },
  { name: "Cisco Systems", category: "technology", description: "Cisco Systems, Inc. designs, manufactures, and sells Internet Protocol based networking products.", domain: "cisco.com", website: "https://www.cisco.com", founded: "1984", employeeRange: "10,001+", headquarters: "San Jose, CA, USA", region: "North America", revenueRange: "$50B+", engagementScore: 87, trustSignals: "Fortune Global 500, Dow 30, Networking leader", tags: "Technology, Networking, Cybersecurity, Cloud", email: "investor-relations@cisco.com", phone: "+1-408-526-4000", highlights: "World's largest networking equipment company", insights: "Pivoting to software-defined networking and security" },
  { name: "Oracle", category: "technology", description: "Oracle Corporation provides products and services addressing enterprise information technology environments worldwide.", domain: "oracle.com", website: "https://www.oracle.com", founded: "1977", employeeRange: "10,001+", headquarters: "Austin, TX, USA", region: "North America", revenueRange: "$50B+", engagementScore: 88, trustSignals: "Fortune Global 500, S&P 500, Cloud infrastructure", tags: "Technology, Cloud Computing, Database, Enterprise Software", email: "investor_relations@oracle.com", phone: "+1-512-338-8000", highlights: "Leading enterprise database and cloud infrastructure provider", insights: "Rapid cloud infrastructure growth challenging AWS and Azure" },
  { name: "Salesforce", category: "technology", description: "Salesforce, Inc. provides CRM technology and enterprise cloud computing solutions.", domain: "salesforce.com", website: "https://www.salesforce.com", founded: "1999", employeeRange: "10,001+", headquarters: "San Francisco, CA, USA", region: "North America", revenueRange: "$30B+", engagementScore: 91, trustSignals: "Fortune Global 500, Dow 30, CRM leader", tags: "Technology, CRM, Cloud Computing, AI, SaaS", email: "investor@salesforce.com", phone: "+1-415-901-7000", highlights: "World's #1 CRM platform, enterprise AI with Einstein", insights: "Integrating generative AI across the entire platform" },
  { name: "SAP", category: "technology", description: "SAP SE develops enterprise application software and related services worldwide.", domain: "sap.com", website: "https://www.sap.com", founded: "1972", employeeRange: "10,001+", headquarters: "Walldorf, Germany", region: "Europe", revenueRange: "$30B+", engagementScore: 86, trustSignals: "Fortune Global 500, Europe's most valuable tech", tags: "Technology, Enterprise Software, ERP, Cloud", email: "investor@sap.com", phone: "+49-6227-7-47474", highlights: "World's largest enterprise software company", insights: "Cloud transformation with RISE with SAP accelerating" },
  { name: "Adobe", category: "technology", description: "Adobe Inc. operates as a diversified software company worldwide with creative, document, and experience cloud solutions.", domain: "adobe.com", website: "https://www.adobe.com", founded: "1982", employeeRange: "10,001+", headquarters: "San Jose, CA, USA", region: "North America", revenueRange: "$20B+", engagementScore: 89, trustSignals: "Fortune Global 500, S&P 500, Creative leader", tags: "Technology, Software, Creative Tools, Marketing, AI", email: "ir@adobe.com", phone: "+1-408-536-6000", highlights: "Industry standard creative and marketing software", insights: "Integrating generative AI (Firefly) across Creative Cloud" },
  { name: "Uber Technologies", category: "technology", description: "Uber Technologies, Inc. develops and operates a technology platform for ride-hailing, food delivery, and freight.", domain: "uber.com", website: "https://www.uber.com", founded: "2009", employeeRange: "10,001+", headquarters: "San Francisco, CA, USA", region: "North America", revenueRange: "$30B+", engagementScore: 86, trustSignals: "Fortune Global 500, S&P 500, Gig economy pioneer", tags: "Technology, Transportation, Food Delivery, Logistics", email: "investor@uber.com", phone: "+1-415-612-8582", highlights: "World's largest ride-hailing and delivery platform", insights: "Achieving sustained profitability, expanding advertising" },
  { name: "Alibaba Group", category: "technology", description: "Alibaba Group Holding Limited provides technology infrastructure and marketing reach for merchants, brands, retailers.", domain: "alibaba.com", website: "https://www.alibaba.com", founded: "1999", employeeRange: "10,001+", headquarters: "Hangzhou, China", region: "Asia-Pacific", revenueRange: "$100B+", engagementScore: 88, trustSignals: "Fortune Global 500, China's largest e-commerce", tags: "Technology, E-Commerce, Cloud Computing, Fintech", email: "ir@alibabagroup.com", phone: "+86-571-8502-2088", highlights: "China's largest e-commerce platform, cloud computing leader", insights: "Restructuring into six business groups for agility" },
  { name: "Tencent Holdings", category: "technology", description: "Tencent Holdings Limited is a Chinese multinational conglomerate in social media, gaming, fintech, and cloud.", domain: "tencent.com", website: "https://www.tencent.com", founded: "1998", employeeRange: "10,001+", headquarters: "Shenzhen, China", region: "Asia-Pacific", revenueRange: "$80B+", engagementScore: 87, trustSignals: "Fortune Global 500, WeChat parent", tags: "Technology, Gaming, Social Media, Fintech, Cloud", email: "ir@tencent.com", phone: "+86-755-8601-3388", highlights: "WeChat ecosystem, world's largest gaming company by revenue", insights: "Expanding international gaming and AI capabilities" },
  { name: "HSBC Holdings", category: "financial services", description: "HSBC Holdings plc is one of the world's largest banking and financial services organizations.", domain: "hsbc.com", website: "https://www.hsbc.com", founded: "1865", employeeRange: "10,001+", headquarters: "London, UK", region: "Europe", revenueRange: "$60B+", engagementScore: 84, trustSignals: "Fortune Global 500, FTSE 100, Global bank", tags: "Banking, Finance, Wealth Management, Trade Finance", email: "investorrelations@hsbc.com", phone: "+44-20-7991-8888", highlights: "Europe's largest bank by assets, strong Asia presence", insights: "Pivoting focus to Asia-Pacific wealth management" },
  { name: "Goldman Sachs", category: "financial services", description: "The Goldman Sachs Group, Inc. is a global investment banking, securities, and investment management firm.", domain: "goldmansachs.com", website: "https://www.goldmansachs.com", founded: "1869", employeeRange: "10,001+", headquarters: "New York, NY, USA", region: "North America", revenueRange: "$40B+", engagementScore: 90, trustSignals: "Fortune Global 500, S&P 500, Top investment bank", tags: "Financial Services, Investment Banking, Asset Management", email: "gs-investor-relations@gs.com", phone: "+1-212-902-1000", highlights: "Leading global investment bank and securities firm", insights: "Refocusing on core investment banking and asset management" },
  { name: "Morgan Stanley", category: "financial services", description: "Morgan Stanley is a global financial services firm providing investment banking, securities, wealth management.", domain: "morganstanley.com", website: "https://www.morganstanley.com", founded: "1935", employeeRange: "10,001+", headquarters: "New York, NY, USA", region: "North America", revenueRange: "$50B+", engagementScore: 88, trustSignals: "Fortune Global 500, S&P 500", tags: "Financial Services, Investment Banking, Wealth Management", email: "investorrelations@morganstanley.com", phone: "+1-212-761-4000", highlights: "Leading wealth management and investment banking firm", insights: "Growing wealth management to $6T+ in client assets" },
  { name: "Citigroup", category: "financial services", description: "Citigroup Inc. is a diversified global financial services holding company.", domain: "citigroup.com", website: "https://www.citigroup.com", founded: "1998", employeeRange: "10,001+", headquarters: "New York, NY, USA", region: "North America", revenueRange: "$70B+", engagementScore: 85, trustSignals: "Fortune Global 500, Dow 30, Global bank", tags: "Banking, Finance, Investment Banking, Global Presence", email: "investor.relations@citi.com", phone: "+1-212-559-1000", highlights: "Most global US bank, operations in 160+ countries", insights: "Simplifying organizational structure for efficiency" },
  { name: "Bank of America", category: "financial services", description: "Bank of America Corporation is one of the world's leading financial institutions.", domain: "bankofamerica.com", website: "https://www.bankofamerica.com", founded: "1998", employeeRange: "10,001+", headquarters: "Charlotte, NC, USA", region: "North America", revenueRange: "$90B+", engagementScore: 87, trustSignals: "Fortune Global 500, Dow 30", tags: "Banking, Finance, Wealth Management, Consumer Banking", email: "investor.relations@bankofamerica.com", phone: "+1-704-386-5681", highlights: "Second-largest US bank, leading consumer banking", insights: "Digital banking innovation with Erica AI assistant" },
  { name: "Wells Fargo", category: "financial services", description: "Wells Fargo & Company is a diversified financial services company providing banking, investment, and mortgage products.", domain: "wellsfargo.com", website: "https://www.wellsfargo.com", founded: "1852", employeeRange: "10,001+", headquarters: "San Francisco, CA, USA", region: "North America", revenueRange: "$70B+", engagementScore: 83, trustSignals: "Fortune Global 500, S&P 500", tags: "Banking, Finance, Mortgage, Consumer Banking", email: "investor.relations@wellsfargo.com", phone: "+1-866-249-3302", highlights: "Fourth-largest US bank, strong mortgage business", insights: "Operational turnaround and regulatory resolution" },
  { name: "ICBC", category: "financial services", description: "Industrial and Commercial Bank of China is the world's largest bank by total assets.", domain: "icbc.com.cn", website: "http://www.icbc.com.cn", founded: "1984", employeeRange: "10,001+", headquarters: "Beijing, China", region: "Asia-Pacific", revenueRange: "$100B+", engagementScore: 80, trustSignals: "Fortune Global 500, World's largest bank", tags: "Banking, Finance, State-owned, China", email: "investor@icbc.com.cn", phone: "+86-10-66108608", highlights: "World's largest bank by total assets", insights: "Expanding fintech and international banking operations" },
  { name: "China Construction Bank", category: "financial services", description: "China Construction Bank Corporation is one of the Big Four banks in China.", domain: "ccb.com", website: "http://www.ccb.com", founded: "1954", employeeRange: "10,001+", headquarters: "Beijing, China", region: "Asia-Pacific", revenueRange: "$100B+", engagementScore: 79, trustSignals: "Fortune Global 500, Big Four China bank", tags: "Banking, Finance, Construction Lending", email: "ir@ccb.com", phone: "+86-10-6759-5000", highlights: "Second-largest bank in China by total assets", insights: "Leading digital banking innovation in China" },
  { name: "Agricultural Bank of China", category: "financial services", description: "Agricultural Bank of China is one of the Big Four banks in China.", domain: "abchina.com", website: "http://www.abchina.com", founded: "1951", employeeRange: "10,001+", headquarters: "Beijing, China", region: "Asia-Pacific", revenueRange: "$100B+", engagementScore: 78, trustSignals: "Fortune Global 500, Big Four China bank", tags: "Banking, Finance, Agricultural Lending", email: "ir@abchina.com", phone: "+86-10-85109619", highlights: "Third-largest bank in China, strong rural banking network", insights: "Expanding digital banking in rural areas" },
  { name: "Bank of China", category: "financial services", description: "Bank of China Limited is one of the Big Four state-owned commercial banks of China.", domain: "boc.cn", website: "http://www.boc.cn", founded: "1912", employeeRange: "10,001+", headquarters: "Beijing, China", region: "Asia-Pacific", revenueRange: "$80B+", engagementScore: 77, trustSignals: "Fortune Global 500, Most international Chinese bank", tags: "Banking, Finance, International Trade", email: "ir@bankofchina.com", phone: "+86-10-6659-6688", highlights: "Most internationally diversified Chinese bank", insights: "Growing cross-border RMB settlement services" },
  { name: "Allianz", category: "financial services", description: "Allianz SE is the largest insurance company in Europe and one of the world's largest financial services groups.", domain: "allianz.com", website: "https://www.allianz.com", founded: "1890", employeeRange: "10,001+", headquarters: "Munich, Germany", region: "Europe", revenueRange: "$100B+", engagementScore: 83, trustSignals: "Fortune Global 500, Europe's largest insurer", tags: "Insurance, Asset Management, Financial Services", email: "investor.relations@allianz.com", phone: "+49-89-3800-0", highlights: "World's largest insurance group, PIMCO parent", insights: "Digital transformation and sustainability-focused products" },
  { name: "AXA", category: "financial services", description: "AXA SA is a French multinational insurance firm.", domain: "axa.com", website: "https://www.axa.com", founded: "1816", employeeRange: "10,001+", headquarters: "Paris, France", region: "Europe", revenueRange: "$80B+", engagementScore: 81, trustSignals: "Fortune Global 500, Global insurer", tags: "Insurance, Financial Services, Asset Management", email: "investorrelations@axa.com", phone: "+33-1-40-75-57-00", highlights: "One of the world's largest insurance companies", insights: "Focusing on health and commercial P&C lines" },
  { name: "Boeing", category: "aerospace & defense", description: "The Boeing Company designs, develops, manufactures, sells, and supports commercial jetliners, defense products, and space systems.", domain: "boeing.com", website: "https://www.boeing.com", founded: "1916", employeeRange: "10,001+", headquarters: "Arlington, VA, USA", region: "North America", revenueRange: "$70B+", engagementScore: 84, trustSignals: "Fortune Global 500, Dow 30, Aerospace leader", tags: "Aerospace, Defense, Aviation, Space", email: "investor.relations@boeing.com", phone: "+1-312-544-2000", highlights: "One of the world's two major aerospace companies", insights: "Recovering production rates and quality focus" },
  { name: "Lockheed Martin", category: "aerospace & defense", description: "Lockheed Martin Corporation is the world's largest defense contractor.", domain: "lockheedmartin.com", website: "https://www.lockheedmartin.com", founded: "1995", employeeRange: "10,001+", headquarters: "Bethesda, MD, USA", region: "North America", revenueRange: "$60B+", engagementScore: 83, trustSignals: "Fortune Global 500, S&P 500, Top defense", tags: "Aerospace, Defense, Technology, Space", email: "investor.relations@lmco.com", phone: "+1-301-897-6000", highlights: "World's largest defense contractor, F-35 program", insights: "Growing space and hypersonic weapons portfolio" },
  { name: "Raytheon Technologies (RTX)", category: "aerospace & defense", description: "RTX Corporation is an aerospace and defense company providing systems and services.", domain: "rtx.com", website: "https://www.rtx.com", founded: "2020", employeeRange: "10,001+", headquarters: "Arlington, VA, USA", region: "North America", revenueRange: "$60B+", engagementScore: 82, trustSignals: "Fortune Global 500, S&P 500", tags: "Aerospace, Defense, Technology, Engines", email: "investor.relations@rtx.com", phone: "+1-781-522-3000", highlights: "Pratt & Whitney engines, Collins Aerospace systems", insights: "Strong defense and commercial aftermarket growth" },
  { name: "General Electric", category: "industrial", description: "GE Aerospace is a global leader in aerospace propulsion, services, and systems.", domain: "ge.com", website: "https://www.geaerospace.com", founded: "1892", employeeRange: "10,001+", headquarters: "Evendale, OH, USA", region: "North America", revenueRange: "$60B+", engagementScore: 85, trustSignals: "Fortune Global 500, S&P 500", tags: "Aerospace, Industrial, Technology, Aviation", email: "investor.communications@ge.com", phone: "+1-617-443-3000", highlights: "World's leading aerospace engine manufacturer", insights: "Pure-play aerospace after GE Vernova energy spinoff" },
  { name: "3M", category: "industrial", description: "3M Company operates as a diversified technology company worldwide in safety, industrial, transportation, and consumer segments.", domain: "3m.com", website: "https://www.3m.com", founded: "1902", employeeRange: "10,001+", headquarters: "St. Paul, MN, USA", region: "North America", revenueRange: "$30B+", engagementScore: 80, trustSignals: "Fortune Global 500, S&P 500", tags: "Industrial, Manufacturing, Consumer Products, Safety", email: "investors@mmm.com", phone: "+1-651-733-1110", highlights: "Diversified manufacturer of industrial and consumer products", insights: "Spun off healthcare business, focusing on core industrial" },
  { name: "Caterpillar", category: "industrial", description: "Caterpillar Inc. is the world's largest manufacturer of construction and mining equipment.", domain: "caterpillar.com", website: "https://www.caterpillar.com", founded: "1925", employeeRange: "10,001+", headquarters: "Irving, TX, USA", region: "North America", revenueRange: "$60B+", engagementScore: 84, trustSignals: "Fortune Global 500, Dow 30", tags: "Industrial, Construction, Mining, Equipment", email: "investor_relations@cat.com", phone: "+1-309-675-1000", highlights: "World's largest construction equipment manufacturer", insights: "Growing autonomous and electric equipment portfolio" },
  { name: "Honeywell", category: "industrial", description: "Honeywell International Inc. is a diversified technology and manufacturing company.", domain: "honeywell.com", website: "https://www.honeywell.com", founded: "1906", employeeRange: "10,001+", headquarters: "Charlotte, NC, USA", region: "North America", revenueRange: "$36B+", engagementScore: 85, trustSignals: "Fortune Global 500, Dow 30", tags: "Industrial, Technology, Aerospace, Building Tech", email: "investor@honeywell.com", phone: "+1-704-627-6200", highlights: "Diversified industrial technology leader", insights: "Focusing on automation, sustainability, and digitalization" },
  { name: "Deere & Company", category: "industrial", description: "Deere & Company manufactures and distributes agricultural, construction, and forestry equipment.", domain: "deere.com", website: "https://www.deere.com", founded: "1837", employeeRange: "10,001+", headquarters: "Moline, IL, USA", region: "North America", revenueRange: "$55B+", engagementScore: 83, trustSignals: "Fortune Global 500, S&P 500", tags: "Agricultural Equipment, Construction, Industrial", email: "investor-relations@johndeere.com", phone: "+1-309-765-8000", highlights: "World's largest agricultural machinery manufacturer", insights: "Leading precision agriculture and autonomous farming technology" },
  { name: "FedEx", category: "logistics", description: "FedEx Corporation provides transportation, e-commerce, and business services worldwide.", domain: "fedex.com", website: "https://www.fedex.com", founded: "1971", employeeRange: "10,001+", headquarters: "Memphis, TN, USA", region: "North America", revenueRange: "$80B+", engagementScore: 85, trustSignals: "Fortune Global 500, S&P 500", tags: "Logistics, Transportation, E-Commerce, Shipping", email: "investor@fedex.com", phone: "+1-901-818-7500", highlights: "World's largest express delivery company", insights: "Integrating FedEx and FedEx Ground networks for efficiency" },
  { name: "UPS", category: "logistics", description: "United Parcel Service, Inc. is the world's largest package delivery company.", domain: "ups.com", website: "https://www.ups.com", founded: "1907", employeeRange: "10,001+", headquarters: "Atlanta, GA, USA", region: "North America", revenueRange: "$90B+", engagementScore: 84, trustSignals: "Fortune Global 500, S&P 500, Dow 30", tags: "Logistics, Transportation, Supply Chain, Delivery", email: "investor@ups.com", phone: "+1-404-828-6000", highlights: "World's largest package delivery company by revenue", insights: "Investing in healthcare logistics and drone delivery" },
  { name: "Deutsche Post DHL", category: "logistics", description: "Deutsche Post DHL Group is the world's largest logistics company.", domain: "dhl.com", website: "https://www.dhl.com", founded: "1969", employeeRange: "10,001+", headquarters: "Bonn, Germany", region: "Europe", revenueRange: "$80B+", engagementScore: 82, trustSignals: "Fortune Global 500, World's largest logistics", tags: "Logistics, Transportation, E-Commerce, Supply Chain", email: "investor.relations@dpdhl.com", phone: "+49-228-182-6301", highlights: "World's largest logistics company, 220+ countries", insights: "Expanding e-commerce logistics and sustainability initiatives" },
  { name: "Home Depot", category: "retail", description: "The Home Depot, Inc. is the world's largest home improvement retailer.", domain: "homedepot.com", website: "https://www.homedepot.com", founded: "1978", employeeRange: "10,001+", headquarters: "Atlanta, GA, USA", region: "North America", revenueRange: "$150B+", engagementScore: 86, trustSignals: "Fortune Global 500, Dow 30, S&P 500", tags: "Retail, Home Improvement, E-Commerce", email: "investor_relations@homedepot.com", phone: "+1-770-433-8211", highlights: "World's largest home improvement retailer", insights: "Growing professional customer segment and same-day delivery" },
  { name: "Target", category: "retail", description: "Target Corporation is a general merchandise retailer in the United States.", domain: "target.com", website: "https://www.target.com", founded: "1902", employeeRange: "10,001+", headquarters: "Minneapolis, MN, USA", region: "North America", revenueRange: "$100B+", engagementScore: 83, trustSignals: "Fortune Global 500, S&P 500", tags: "Retail, E-Commerce, Consumer Goods", email: "investorrelations@target.com", phone: "+1-612-304-6073", highlights: "America's fourth-largest retailer, drive-up and delivery", insights: "Enhancing digital capabilities and own-brand portfolio" },
  { name: "LVMH", category: "consumer goods", description: "LVMH Moët Hennessy Louis Vuitton is the world's largest luxury goods conglomerate.", domain: "lvmh.com", website: "https://www.lvmh.com", founded: "1987", employeeRange: "10,001+", headquarters: "Paris, France", region: "Europe", revenueRange: "$80B+", engagementScore: 90, trustSignals: "Fortune Global 500, World's largest luxury group", tags: "Luxury, Fashion, Wines & Spirits, Watches, Jewelry", email: "investor.relations@lvmh.com", phone: "+33-1-44-13-22-22", highlights: "75+ luxury brands including Louis Vuitton, Dior, Tiffany", insights: "Strong demand from affluent consumers driving growth" },
  { name: "Unilever", category: "consumer goods", description: "Unilever PLC operates as a consumer goods company worldwide.", domain: "unilever.com", website: "https://www.unilever.com", founded: "1929", employeeRange: "10,001+", headquarters: "London, UK", region: "Europe", revenueRange: "$60B+", engagementScore: 85, trustSignals: "Fortune Global 500, FTSE 100", tags: "Consumer Goods, FMCG, Personal Care, Food", email: "investor.relations@unilever.com", phone: "+44-20-7822-5252", highlights: "400+ brands including Dove, Ben & Jerry's, Knorr", insights: "Focused on growth action plan and power brands strategy" },
  { name: "L'Oréal", category: "consumer goods", description: "L'Oréal S.A. is the world's largest cosmetics and beauty company.", domain: "loreal.com", website: "https://www.loreal.com", founded: "1909", employeeRange: "10,001+", headquarters: "Clichy, France", region: "Europe", revenueRange: "$40B+", engagementScore: 86, trustSignals: "Fortune Global 500, Beauty market leader", tags: "Consumer Goods, Beauty, Cosmetics, Personal Care", email: "investor.relations@loreal.com", phone: "+33-1-47-56-70-00", highlights: "World's largest cosmetics company, 37 brands", insights: "Leading beauty tech innovation and e-commerce growth" },
  { name: "BMW Group", category: "automotive", description: "Bayerische Motoren Werke AG is a German multinational manufacturer of luxury vehicles and motorcycles.", domain: "bmw.com", website: "https://www.bmw.com", founded: "1916", employeeRange: "10,001+", headquarters: "Munich, Germany", region: "Europe", revenueRange: "$150B+", engagementScore: 87, trustSignals: "Fortune Global 500, DAX, Luxury automaker", tags: "Automotive, Luxury Vehicles, Electric Vehicles", email: "investor.relations@bmw.de", phone: "+49-89-382-0", highlights: "Leading luxury automaker, BMW, MINI, Rolls-Royce brands", insights: "Neue Klasse EV platform launching, circular economy focus" },
  { name: "Mercedes-Benz Group", category: "automotive", description: "Mercedes-Benz Group AG is one of the world's leading manufacturers of premium and luxury cars and vans.", domain: "mercedes-benz.com", website: "https://group.mercedes-benz.com", founded: "1926", employeeRange: "10,001+", headquarters: "Stuttgart, Germany", region: "Europe", revenueRange: "$150B+", engagementScore: 87, trustSignals: "Fortune Global 500, DAX, Luxury automaker", tags: "Automotive, Luxury Vehicles, Electric Vehicles", email: "ir@mercedes-benz.com", phone: "+49-711-17-0", highlights: "Iconic luxury car brand, strong EV lineup", insights: "Luxury-focused EV strategy with MB.OS digital platform" },
  { name: "Hyundai Motor", category: "automotive", description: "Hyundai Motor Company is a South Korean multinational automotive manufacturer.", domain: "hyundai.com", website: "https://www.hyundai.com", founded: "1967", employeeRange: "10,001+", headquarters: "Seoul, South Korea", region: "Asia-Pacific", revenueRange: "$100B+", engagementScore: 84, trustSignals: "Fortune Global 500, Global automaker", tags: "Automotive, Electric Vehicles, Hydrogen, Mobility", email: "ir@hyundai.com", phone: "+82-2-3464-1114", highlights: "Third-largest automaker globally including Kia", insights: "Leading in hydrogen fuel cell and EV technology" },
  { name: "General Motors", category: "automotive", description: "General Motors Company designs, builds, and sells trucks, crossovers, cars, and automobile parts worldwide.", domain: "gm.com", website: "https://www.gm.com", founded: "1908", employeeRange: "10,001+", headquarters: "Detroit, MI, USA", region: "North America", revenueRange: "$170B+", engagementScore: 83, trustSignals: "Fortune Global 500, S&P 500", tags: "Automotive, Electric Vehicles, Trucks, Mobility", email: "investor.relations@gm.com", phone: "+1-313-667-1500", highlights: "America's largest automaker, Ultium EV platform", insights: "Scaling EV production and autonomous driving" },
  { name: "Ford Motor", category: "automotive", description: "Ford Motor Company designs, manufactures, and sells automobiles and commercial vehicles worldwide.", domain: "ford.com", website: "https://www.ford.com", founded: "1903", employeeRange: "10,001+", headquarters: "Dearborn, MI, USA", region: "North America", revenueRange: "$170B+", engagementScore: 82, trustSignals: "Fortune Global 500, S&P 500", tags: "Automotive, Electric Vehicles, Trucks, Commercial", email: "stockholder@ford.com", phone: "+1-313-322-3000", highlights: "Iconic American automaker, F-150 Lightning pioneer", insights: "Balancing ICE profitability with EV investment" },
  { name: "Honda Motor", category: "automotive", description: "Honda Motor Co., Ltd. develops, manufactures, and distributes motorcycles, automobiles, and power products worldwide.", domain: "honda.com", website: "https://global.honda", founded: "1948", employeeRange: "10,001+", headquarters: "Tokyo, Japan", region: "Asia-Pacific", revenueRange: "$120B+", engagementScore: 83, trustSignals: "Fortune Global 500, Global automaker", tags: "Automotive, Motorcycles, Power Products, Robotics", email: "csr@honda.co.jp", phone: "+81-3-3423-1111", highlights: "World's largest motorcycle manufacturer and major automaker", insights: "Launching series of new EVs and exploring hydrogen fuel cells" },
  { name: "Stellantis", category: "automotive", description: "Stellantis N.V. is a multinational automotive company formed from the merger of FCA and PSA.", domain: "stellantis.com", website: "https://www.stellantis.com", founded: "2021", employeeRange: "10,001+", headquarters: "Amsterdam, Netherlands", region: "Europe", revenueRange: "$180B+", engagementScore: 80, trustSignals: "Fortune Global 500, Global automaker", tags: "Automotive, Electric Vehicles, Commercial Vehicles", email: "ir@stellantis.com", phone: "+31-20-891-4800", highlights: "14 iconic brands: Jeep, Dodge, Fiat, Peugeot, Citroën", insights: "Electrification strategy across all brands by 2030" },
  { name: "Mitsubishi Corporation", category: "conglomerate", description: "Mitsubishi Corporation is Japan's largest general trading company (sogo shosha).", domain: "mitsubishicorp.com", website: "https://www.mitsubishicorp.com", founded: "1950", employeeRange: "10,001+", headquarters: "Tokyo, Japan", region: "Asia-Pacific", revenueRange: "$150B+", engagementScore: 79, trustSignals: "Fortune Global 500, Japan's largest trading house", tags: "Conglomerate, Trading, Energy, Infrastructure", email: "ir@mitsubishicorp.com", phone: "+81-3-3210-2121", highlights: "Japan's largest diversified trading company", insights: "Expanding renewable energy and EV battery materials" },
  { name: "Ping An Insurance", category: "financial services", description: "Ping An Insurance (Group) Company of China is the world's largest insurance company by revenue.", domain: "pingan.cn", website: "https://www.pingan.cn", founded: "1988", employeeRange: "10,001+", headquarters: "Shenzhen, China", region: "Asia-Pacific", revenueRange: "$150B+", engagementScore: 81, trustSignals: "Fortune Global 500, World's largest insurer", tags: "Insurance, Financial Services, Technology, Healthcare", email: "ir@pingan.com.cn", phone: "+86-755-2262-3355", highlights: "World's largest insurance company, fintech innovator", insights: "Leading AI-powered insurance and healthcare integration" },
  { name: "Berkshire's GEICO", category: "financial services", description: "Note: GEICO is part of Berkshire Hathaway. Including separately for reference.", domain: "geico.com", website: "https://www.geico.com", founded: "1936", employeeRange: "10,001+", headquarters: "Chevy Chase, MD, USA", region: "North America", revenueRange: "$40B+", engagementScore: 76, trustSignals: "Berkshire Hathaway subsidiary", tags: "Insurance, Auto Insurance, Consumer", email: "corporate@geico.com", phone: "+1-301-986-3000", highlights: "Second-largest auto insurer in the US", insights: "Digital-first approach to auto insurance" },
  { name: "Accenture", category: "information technology & services", description: "Accenture plc is a global professional services company providing consulting, technology, and outsourcing services.", domain: "accenture.com", website: "https://www.accenture.com", founded: "1989", employeeRange: "10,001+", headquarters: "Dublin, Ireland", region: "Europe", revenueRange: "$60B+", engagementScore: 89, trustSignals: "Fortune Global 500, S&P 500", tags: "IT Services, Consulting, Digital Transformation, AI", email: "investor.relations@accenture.com", phone: "+1-312-842-5012", highlights: "World's largest IT services company, 700K+ employees", insights: "Leading enterprise AI implementation and digital transformation" },
  { name: "Infosys", category: "information technology & services", description: "Infosys Limited provides consulting, technology, outsourcing, and next-generation digital services.", domain: "infosys.com", website: "https://www.infosys.com", founded: "1981", employeeRange: "10,001+", headquarters: "Bengaluru, India", region: "Asia-Pacific", revenueRange: "$15B+", engagementScore: 85, trustSignals: "Fortune Global 500, BSE Sensex", tags: "IT Services, Consulting, Digital Transformation, AI", email: "investors@infosys.com", phone: "+91-80-2852-0261", highlights: "India's second-largest IT services company", insights: "Growing AI and cloud services capabilities" },
  { name: "TCS (Tata Consultancy Services)", category: "information technology & services", description: "Tata Consultancy Services Limited is an Indian multinational IT services and consulting company.", domain: "tcs.com", website: "https://www.tcs.com", founded: "1968", employeeRange: "10,001+", headquarters: "Mumbai, India", region: "Asia-Pacific", revenueRange: "$25B+", engagementScore: 86, trustSignals: "Fortune Global 500, BSE Sensex, India's most valuable IT", tags: "IT Services, Consulting, Digital Transformation", email: "investor.relations@tcs.com", phone: "+91-22-6778-9595", highlights: "India's largest IT services company, 600K+ employees", insights: "Leading AI-powered enterprise transformation services" },
  { name: "Wipro", category: "information technology & services", description: "Wipro Limited is a global information technology, consulting, and business process services company.", domain: "wipro.com", website: "https://www.wipro.com", founded: "1945", employeeRange: "10,001+", headquarters: "Bengaluru, India", region: "Asia-Pacific", revenueRange: "$10B+", engagementScore: 82, trustSignals: "Fortune Global 500, BSE Sensex", tags: "IT Services, Consulting, Digital Transformation", email: "investor@wipro.com", phone: "+91-80-2844-0011", highlights: "India's third-largest IT services company", insights: "AI-first strategy and large deal momentum" },
  { name: "HCLTech", category: "information technology & services", description: "HCLTech (HCL Technologies Limited) is a multinational IT services and consulting company.", domain: "hcltech.com", website: "https://www.hcltech.com", founded: "1991", employeeRange: "10,001+", headquarters: "Noida, India", region: "Asia-Pacific", revenueRange: "$12B+", engagementScore: 83, trustSignals: "Fortune Global 500, BSE Sensex", tags: "IT Services, Engineering, Cloud, Cybersecurity", email: "investor.relations@hcltech.com", phone: "+91-120-404-0000", highlights: "India's fourth-largest IT services company", insights: "Strong in engineering services and GenAI solutions" },
  { name: "Reliance Industries", category: "conglomerate", description: "Reliance Industries Limited is India's largest private sector company, a conglomerate with interests in energy, petrochemicals, retail, and telecom.", domain: "ril.com", website: "https://www.ril.com", founded: "1966", employeeRange: "10,001+", headquarters: "Mumbai, India", region: "Asia-Pacific", revenueRange: "$100B+", engagementScore: 88, trustSignals: "Fortune Global 500, India's largest company", tags: "Conglomerate, Energy, Retail, Telecom, Technology", email: "investor_relations@ril.com", phone: "+91-22-3555-5000", highlights: "India's most valuable company, Jio telecom, Reliance Retail", insights: "Expanding new energy business and retail ecosystem" },
  { name: "Tata Motors", category: "automotive", description: "Tata Motors Limited is an Indian multinational automotive manufacturing company, including Jaguar Land Rover.", domain: "tatamotors.com", website: "https://www.tatamotors.com", founded: "1945", employeeRange: "10,001+", headquarters: "Mumbai, India", region: "Asia-Pacific", revenueRange: "$40B+", engagementScore: 82, trustSignals: "Fortune Global 500, BSE Sensex", tags: "Automotive, Electric Vehicles, Commercial Vehicles", email: "investor.relations@tatamotors.com", phone: "+91-22-6665-8282", highlights: "India's largest automaker, owns Jaguar Land Rover", insights: "Leading India's EV market and premium luxury recovery" },
  { name: "State Bank of India", category: "financial services", description: "State Bank of India is the country's largest commercial bank.", domain: "sbi.co.in", website: "https://www.sbi.co.in", founded: "1806", employeeRange: "10,001+", headquarters: "Mumbai, India", region: "Asia-Pacific", revenueRange: "$50B+", engagementScore: 80, trustSignals: "Fortune Global 500, India's largest bank", tags: "Banking, Finance, Government", email: "investor.relations@sbi.co.in", phone: "+91-22-2274-0841", highlights: "India's largest bank with 440M+ customers", insights: "Digital banking transformation with YONO platform" },
  { name: "Indian Oil Corporation", category: "energy & utilities", description: "Indian Oil Corporation Limited is India's largest commercial enterprise.", domain: "iocl.com", website: "https://www.iocl.com", founded: "1959", employeeRange: "10,001+", headquarters: "New Delhi, India", region: "Asia-Pacific", revenueRange: "$80B+", engagementScore: 78, trustSignals: "Fortune Global 500, India's largest company by revenue", tags: "Oil & Gas, Energy, Refining, Petrochemicals", email: "investors@iocl.co.in", phone: "+91-11-2643-8001", highlights: "India's largest commercial enterprise by revenue", insights: "Expanding green hydrogen and biofuel capabilities" },
  { name: "Rajesh Exports", category: "consumer goods", description: "Rajesh Exports Limited is one of the world's largest gold companies.", domain: "rajeshexports.com", website: "http://www.rajeshexports.com", founded: "1990", employeeRange: "1,001-5,000", headquarters: "Bengaluru, India", region: "Asia-Pacific", revenueRange: "$30B+", engagementScore: 72, trustSignals: "Fortune Global 500, BSE listed", tags: "Gold, Jewelry, Mining, Consumer Goods", email: "investors@rajeshexports.com", phone: "+91-80-4153-5000", highlights: "World's largest gold refining company", insights: "Expanding retail jewelry brand Shubh Jewellers" },
  { name: "Mahindra Group", category: "conglomerate", description: "Mahindra Group is an Indian multinational conglomerate with interests in automotive, IT, defense, and more.", domain: "mahindra.com", website: "https://www.mahindra.com", founded: "1945", employeeRange: "10,001+", headquarters: "Mumbai, India", region: "Asia-Pacific", revenueRange: "$20B+", engagementScore: 81, trustSignals: "Fortune Global 500, India conglomerate", tags: "Automotive, IT, Agriculture, Defense, Real Estate", email: "investor.relations@mahindra.com", phone: "+91-22-2490-1441", highlights: "India's leading SUV manufacturer and IT services", insights: "Launching new EV platform and expanding electric SUV lineup" },
  { name: "BHP Group", category: "mining & metals", description: "BHP Group Limited is the world's largest mining company.", domain: "bhp.com", website: "https://www.bhp.com", founded: "1885", employeeRange: "10,001+", headquarters: "Melbourne, Australia", region: "Asia-Pacific", revenueRange: "$50B+", engagementScore: 82, trustSignals: "Fortune Global 500, World's largest miner", tags: "Mining, Iron Ore, Copper, Coal, Metals", email: "investor.relations@bhp.com", phone: "+61-3-9609-3333", highlights: "World's largest mining company by market cap", insights: "Focusing on future-facing commodities: copper, potash, nickel" },
  { name: "Rio Tinto", category: "mining & metals", description: "Rio Tinto Group is a multinational mining and metals corporation.", domain: "riotinto.com", website: "https://www.riotinto.com", founded: "1873", employeeRange: "10,001+", headquarters: "London, UK", region: "Europe", revenueRange: "$50B+", engagementScore: 81, trustSignals: "Fortune Global 500, FTSE 100, Major miner", tags: "Mining, Iron Ore, Aluminum, Copper, Lithium", email: "investor.relations@riotinto.com", phone: "+44-20-7781-2000", highlights: "Second-largest mining company globally", insights: "Expanding lithium and copper for energy transition" },
  { name: "Vale", category: "mining & metals", description: "Vale S.A. is the world's largest producer of iron ore and nickel.", domain: "vale.com", website: "https://www.vale.com", founded: "1942", employeeRange: "10,001+", headquarters: "Rio de Janeiro, Brazil", region: "South America", revenueRange: "$40B+", engagementScore: 79, trustSignals: "Fortune Global 500, B3 listed", tags: "Mining, Iron Ore, Nickel, Copper, Metals", email: "investor.relations@vale.com", phone: "+55-21-3485-3900", highlights: "World's largest iron ore producer", insights: "Expanding nickel production for EV battery supply chain" },
  { name: "Starbucks", category: "food & beverage", description: "Starbucks Corporation is the world's largest coffeehouse chain.", domain: "starbucks.com", website: "https://www.starbucks.com", founded: "1971", employeeRange: "10,001+", headquarters: "Seattle, WA, USA", region: "North America", revenueRange: "$35B+", engagementScore: 88, trustSignals: "Fortune Global 500, S&P 500, Iconic brand", tags: "Food & Beverage, Restaurant, Retail, Coffee", email: "investor.relations@starbucks.com", phone: "+1-206-318-7100", highlights: "World's largest coffeehouse chain, 35,000+ stores", insights: "Reinvention plan and expanding into new markets" },
  { name: "McDonald's", category: "food & beverage", description: "McDonald's Corporation is the world's largest restaurant company by revenue.", domain: "mcdonalds.com", website: "https://www.mcdonalds.com", founded: "1940", employeeRange: "10,001+", headquarters: "Chicago, IL, USA", region: "North America", revenueRange: "$25B+", engagementScore: 89, trustSignals: "Fortune Global 500, Dow 30, Iconic brand", tags: "Food & Beverage, Restaurant, Quick Service, Franchise", email: "investor.relations@us.mcd.com", phone: "+1-630-623-3000", highlights: "World's most recognized restaurant brand, 40,000+ locations", insights: "Expanding digital ordering and loyalty program" },
  { name: "Airbus", category: "aerospace & defense", description: "Airbus SE is a European multinational aerospace corporation.", domain: "airbus.com", website: "https://www.airbus.com", founded: "1970", employeeRange: "10,001+", headquarters: "Leiden, Netherlands", region: "Europe", revenueRange: "$70B+", engagementScore: 85, trustSignals: "Fortune Global 500, CAC 40, Europe's largest aerospace", tags: "Aerospace, Defense, Space, Aviation", email: "investor.relations@airbus.com", phone: "+33-5-61-93-33-33", highlights: "World's largest commercial aircraft manufacturer by orders", insights: "Record order backlog and ramping up A320 production rates" },
  { name: "Deutsche Telekom", category: "telecommunications", description: "Deutsche Telekom AG is one of the world's largest telecommunications companies.", domain: "telekom.com", website: "https://www.telekom.com", founded: "1995", employeeRange: "10,001+", headquarters: "Bonn, Germany", region: "Europe", revenueRange: "$100B+", engagementScore: 82, trustSignals: "Fortune Global 500, DAX, T-Mobile parent", tags: "Telecommunications, Mobile, Internet, IT Services", email: "investor.relations@telekom.de", phone: "+49-228-181-88880", highlights: "Parent of T-Mobile US, Europe's largest telco", insights: "T-Mobile US driving growth, 5G network leadership" },
  { name: "Verizon Communications", category: "telecommunications", description: "Verizon Communications Inc. is a leading provider of telecommunications and technology solutions.", domain: "verizon.com", website: "https://www.verizon.com", founded: "2000", employeeRange: "10,001+", headquarters: "New York, NY, USA", region: "North America", revenueRange: "$130B+", engagementScore: 83, trustSignals: "Fortune Global 500, Dow 30", tags: "Telecommunications, 5G, Internet, Mobile", email: "investor.relations@verizon.com", phone: "+1-212-395-1525", highlights: "Largest US wireless carrier, 5G network leader", insights: "Fixed wireless access growth and network monetization" },
  { name: "AT&T", category: "telecommunications", description: "AT&T Inc. is a multinational telecommunications holding company.", domain: "att.com", website: "https://www.att.com", founded: "1983", employeeRange: "10,001+", headquarters: "Dallas, TX, USA", region: "North America", revenueRange: "$120B+", engagementScore: 82, trustSignals: "Fortune Global 500, S&P 500", tags: "Telecommunications, 5G, Internet, Media", email: "investor.relations@att.com", phone: "+1-210-821-4105", highlights: "One of the world's largest telecom companies", insights: "Focused on 5G and fiber after media business separation" },
  { name: "Comcast", category: "telecommunications", description: "Comcast Corporation is a global media and technology company and the largest cable TV company.", domain: "comcast.com", website: "https://www.comcastcorporation.com", founded: "1963", employeeRange: "10,001+", headquarters: "Philadelphia, PA, USA", region: "North America", revenueRange: "$120B+", engagementScore: 82, trustSignals: "Fortune Global 500, S&P 500", tags: "Telecommunications, Media, Entertainment, Broadband", email: "investor_relations@comcast.com", phone: "+1-215-286-1700", highlights: "Largest cable company, NBCUniversal, Sky media", insights: "Growing broadband and streaming with Peacock" },
  { name: "T-Mobile US", category: "telecommunications", description: "T-Mobile US, Inc. is the third-largest wireless carrier in the United States.", domain: "t-mobile.com", website: "https://www.t-mobile.com", founded: "1994", employeeRange: "10,001+", headquarters: "Bellevue, WA, USA", region: "North America", revenueRange: "$70B+", engagementScore: 84, trustSignals: "Fortune Global 500, S&P 500", tags: "Telecommunications, 5G, Mobile, Wireless", email: "investor.relations@t-mobile.com", phone: "+1-425-378-4000", highlights: "Fastest-growing US wireless carrier, 5G leader", insights: "Leading 5G network coverage and fixed wireless broadband" },
  { name: "Huawei Technologies", category: "technology", description: "Huawei Technologies Co., Ltd. is a Chinese multinational technology company and the world's largest telecom equipment manufacturer.", domain: "huawei.com", website: "https://www.huawei.com", founded: "1987", employeeRange: "10,001+", headquarters: "Shenzhen, China", region: "Asia-Pacific", revenueRange: "$90B+", engagementScore: 80, trustSignals: "Fortune Global 500, Telecom equipment leader", tags: "Technology, Telecommunications, 5G, Cloud, Consumer Electronics", email: "ir@huawei.com", phone: "+86-755-2878-0808", highlights: "World's largest telecom equipment maker, growing cloud", insights: "Developing domestic semiconductor alternatives and HarmonyOS" },
  { name: "BASF", category: "chemicals", description: "BASF SE is the world's largest chemical producer.", domain: "basf.com", website: "https://www.basf.com", founded: "1865", employeeRange: "10,001+", headquarters: "Ludwigshafen, Germany", region: "Europe", revenueRange: "$70B+", engagementScore: 80, trustSignals: "Fortune Global 500, DAX, World's largest chemical company", tags: "Chemicals, Materials, Industrial, Agriculture", email: "investor.relations@basf.com", phone: "+49-621-60-0", highlights: "World's largest chemical company by revenue", insights: "Investing in battery materials and sustainable chemistry" },
  { name: "Dow Chemical", category: "chemicals", description: "Dow Inc. is a global leader in materials science, delivering innovative and sustainable solutions.", domain: "dow.com", website: "https://www.dow.com", founded: "2019", employeeRange: "10,001+", headquarters: "Midland, MI, USA", region: "North America", revenueRange: "$40B+", engagementScore: 78, trustSignals: "Fortune Global 500, Dow 30", tags: "Chemicals, Materials Science, Packaging, Infrastructure", email: "investor@dow.com", phone: "+1-989-636-1000", highlights: "Major materials science company", insights: "Leading circularity and net-zero emissions initiatives" },
  { name: "TSMC", category: "technology", description: "Taiwan Semiconductor Manufacturing Company is the world's largest dedicated semiconductor foundry.", domain: "tsmc.com", website: "https://www.tsmc.com", founded: "1987", employeeRange: "10,001+", headquarters: "Hsinchu, Taiwan", region: "Asia-Pacific", revenueRange: "$70B+", engagementScore: 93, trustSignals: "Fortune Global 500, World's largest chip foundry", tags: "Technology, Semiconductors, Manufacturing, AI", email: "invest@tsmc.com", phone: "+886-3-568-8100", highlights: "Makes chips for Apple, NVIDIA, AMD — world's most advanced foundry", insights: "Building fabs in US, Japan, Europe for supply chain resilience" },
  { name: "PayPal Holdings", category: "financial services", description: "PayPal Holdings, Inc. is a global fintech company operating a worldwide online payments system.", domain: "paypal.com", website: "https://www.paypal.com", founded: "1998", employeeRange: "10,001+", headquarters: "San Jose, CA, USA", region: "North America", revenueRange: "$30B+", engagementScore: 85, trustSignals: "Fortune Global 500, S&P 500", tags: "Fintech, Payments, E-Commerce, Digital Wallet", email: "investor@paypal.com", phone: "+1-408-967-1000", highlights: "400M+ active accounts, leading digital payments platform", insights: "Revamping checkout experience and launching stablecoin" },
  { name: "ServiceNow", category: "technology", description: "ServiceNow, Inc. provides enterprise cloud computing solutions for digital workflows.", domain: "servicenow.com", website: "https://www.servicenow.com", founded: "2004", employeeRange: "10,001+", headquarters: "Santa Clara, CA, USA", region: "North America", revenueRange: "$9B+", engagementScore: 88, trustSignals: "Fortune Global 500, S&P 500, Enterprise workflow leader", tags: "Technology, SaaS, Enterprise, AI, Automation", email: "ir@servicenow.com", phone: "+1-408-501-8550", highlights: "Enterprise workflow automation leader, rapid growth", insights: "AI-powered platform transforming enterprise operations" },
  { name: "Broadcom", category: "technology", description: "Broadcom Inc. is a global technology company that designs, develops, and supplies semiconductor and infrastructure software.", domain: "broadcom.com", website: "https://www.broadcom.com", founded: "1961", employeeRange: "10,001+", headquarters: "Palo Alto, CA, USA", region: "North America", revenueRange: "$35B+", engagementScore: 87, trustSignals: "Fortune Global 500, S&P 500", tags: "Technology, Semiconductors, Infrastructure Software, Networking", email: "investor.relations@broadcom.com", phone: "+1-408-433-8000", highlights: "Major semiconductor and enterprise software company", insights: "VMware acquisition creating enterprise infrastructure giant" },
  { name: "AMD", category: "technology", description: "Advanced Micro Devices, Inc. is a global semiconductor company developing computer processors and related technologies.", domain: "amd.com", website: "https://www.amd.com", founded: "1969", employeeRange: "10,001+", headquarters: "Santa Clara, CA, USA", region: "North America", revenueRange: "$20B+", engagementScore: 88, trustSignals: "Fortune Global 500, S&P 500", tags: "Technology, Semiconductors, AI, Data Center, Gaming", email: "ir@amd.com", phone: "+1-408-749-4000", highlights: "Leading CPU and GPU maker, growing AI chip portfolio", insights: "MI300 AI accelerator challenging NVIDIA in data centers" },
  { name: "Qualcomm", category: "technology", description: "Qualcomm Incorporated develops and commercializes foundational technologies for the wireless industry worldwide.", domain: "qualcomm.com", website: "https://www.qualcomm.com", founded: "1985", employeeRange: "10,001+", headquarters: "San Diego, CA, USA", region: "North America", revenueRange: "$35B+", engagementScore: 85, trustSignals: "Fortune Global 500, S&P 500, Mobile chip leader", tags: "Technology, Semiconductors, 5G, Mobile, IoT", email: "ir@qualcomm.com", phone: "+1-858-587-1121", highlights: "Snapdragon mobile processor leader, 5G modem pioneer", insights: "Expanding into automotive, IoT, and AI PC markets" },
  { name: "Spotify Technology", category: "technology", description: "Spotify Technology S.A. is the world's largest music streaming platform.", domain: "spotify.com", website: "https://www.spotify.com", founded: "2006", employeeRange: "5,001-10,000", headquarters: "Stockholm, Sweden", region: "Europe", revenueRange: "$14B+", engagementScore: 84, trustSignals: "Fortune Global 500, Global streaming leader", tags: "Technology, Music, Streaming, Entertainment, Podcasts", email: "ir@spotify.com", phone: "+46-8-546-500-00", highlights: "600M+ users, world's largest audio streaming service", insights: "Achieving profitability through operational efficiency" },
];

async function main() {
  // Find the default workspace
  const workspace = await prisma.workspace.findFirst();
  if (!workspace) {
    console.error("No workspace found. Please seed a workspace first.");
    process.exit(1);
  }

  console.log(`\n🏢 Seeding ${fortune500Companies.length} Fortune Global 500 companies...`);
  console.log(`   Workspace: ${workspace.name} (${workspace.id})\n`);

  let created = 0;
  let updated = 0;
  let skipped = 0;

  for (const company of fortune500Companies) {
    try {
      // Check if company already exists by domain
      const existing = await prisma.company.findFirst({
        where: {
          domain: company.domain,
          workspaceId: workspace.id,
        },
      });

      if (existing) {
        // Update engagement score and key fields to ensure proper display
        await prisma.company.update({
          where: { id: existing.id },
          data: {
            engagementScore: company.engagementScore,
            description: company.description,
            revenueRange: company.revenueRange,
            trustSignals: company.trustSignals,
            highlights: company.highlights,
            insights: company.insights,
          },
        });
        updated++;
        continue;
      }

      await prisma.company.create({
        data: {
          workspaceId: workspace.id,
          name: company.name,
          category: company.category,
          description: company.description,
          domain: company.domain,
          website: company.website,
          founded: company.founded,
          employeeRange: company.employeeRange,
          headquarters: company.headquarters,
          region: company.region,
          revenueRange: company.revenueRange,
          engagementScore: company.engagementScore,
          trustSignals: company.trustSignals,
          tags: company.tags,
          email: company.email,
          phone: company.phone,
          highlights: company.highlights,
          insights: company.insights,
        },
      });
      created++;
    } catch (err: any) {
      console.error(`   ❌ Failed to seed "${company.name}": ${err.message}`);
      skipped++;
    }
  }

  console.log(`\n✅ Seeding complete!`);
  console.log(`   Created: ${created}`);
  console.log(`   Updated: ${updated}`);
  console.log(`   Skipped: ${skipped}`);
  console.log(`   Total:   ${fortune500Companies.length}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
