import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient({ log: ["error"] });

const CATEGORY = "information technology & services";
const REGION_INDIA = "Asia-Pacific";

// ── 30 Real Indian IT MNCs ──────────────────────────────────────────
const indianITMncs = [
  {
    name: "Tata Consultancy Services",
    domain: "tcs.com",
    description: "Tata Consultancy Services (TCS) is an Indian multinational information technology services and consulting company headquartered in Mumbai. It is part of the Tata Group and operates in 150 locations across 46 countries.",
    founded: "1968",
    employeeRange: "10001+",
    headquarters: "Mumbai, India",
    revenueRange: "$1B+",
    engagementScore: 100,
    tags: "IT Services, Consulting, Digital Transformation, Tata Group",
    highlights: "Largest IT company in India by market cap, Global Top 10 IT services, TCS Digital innovation lab",
    insights: "Strategic leader in enterprise digital transformation, strong government and BFSI vertical",
    email: "global.communications@tcs.com",
    phone: "+91 22 6778 9999",
  },
  {
    name: "Infosys",
    domain: "infosys.com",
    description: "Infosys Limited is an Indian multinational corporation that provides business consulting, information technology, and outsourcing services. Co-founded by N. R. Narayana Murthy, it is the second-largest Indian IT company.",
    founded: "1981",
    employeeRange: "10001+",
    headquarters: "Bangalore, India",
    revenueRange: "$1B+",
    engagementScore: 99,
    tags: "IT Services, Consulting, Digital, AI, Cloud",
    highlights: "Infosys BPM, InfyMe platform, Infosys Nia AI, Global delivery model pioneer",
    insights: "Strong in cloud migration and digital experience, rapid AI adoption across verticals",
    email: "askus@infosys.com",
    phone: "+91 80 2852 0261",
  },
  {
    name: "Wipro",
    domain: "wipro.com",
    description: "Wipro Limited is an Indian multinational corporation that provides information technology, consulting, and business process services. Headquartered in Bangalore, it is the third-largest Indian IT company.",
    founded: "1945",
    employeeRange: "10001+",
    headquarters: "Bangalore, India",
    revenueRange: "$1B+",
    engagementScore: 99,
    tags: "IT Services, Consulting, Digital Operations, Cloud",
    highlights: "Wipro HOLMES AI, FullStride Cloud Services, Sustainability leadership in IT",
    insights: "Strong enterprise cloud and cybersecurity practice, growing European footprint",
    email: "info@wipro.com",
    phone: "+91 80 2844 0011",
  },
  {
    name: "HCL Technologies",
    domain: "hcltech.com",
    description: "HCL Technologies is an Indian multinational IT services and consulting company headquartered in Noida. It is a next-generation global technology company helping enterprises reimagine their businesses for the digital age.",
    founded: "1991",
    employeeRange: "10001+",
    headquarters: "Noida, India",
    revenueRange: "$1B+",
    engagementScore: 98,
    tags: "IT Services, Engineering, Cloud, Digital, IoT",
    highlights: "HCL DRYiCE AI platform, Mode 1-2-3 strategy, Strong in engineering and R&D services",
    insights: "Industry leader in IT infrastructure management and product engineering services",
    email: "info@hcltech.com",
    phone: "+91 120 431 4000",
  },
  {
    name: "Tech Mahindra",
    domain: "techmahindra.com",
    description: "Tech Mahindra is an Indian multinational technology company providing IT and business process outsourcing services. A subsidiary of the Mahindra Group, it is focused on digital transformation and telecom sector solutions.",
    founded: "1986",
    employeeRange: "10001+",
    headquarters: "Pune, India",
    revenueRange: "$1B+",
    engagementScore: 98,
    tags: "IT Services, Telecom, Digital, 5G, Consulting",
    highlights: "TechM NXT.NOW framework, Telecom industry leader, Maker's Lab innovation center",
    insights: "Leading telecom and media vertical expertise, strong 5G and edge computing capabilities",
    email: "media.relations@techmahindra.com",
    phone: "+91 20 3054 5000",
  },
  {
    name: "L&T Technology Services",
    domain: "ltts.com",
    description: "L&T Technology Services (LTTS) is a global leader in engineering and R&D services. A subsidiary of Larsen & Toubro, it serves multiple industries including automotive, industrial products, medical devices, and telecom.",
    founded: "2012",
    employeeRange: "10001+",
    headquarters: "Mumbai, India",
    revenueRange: "$500M - $1B",
    engagementScore: 97,
    tags: "Engineering R&D, IoT, Digital Engineering, Industry 4.0",
    highlights: "Engineering R&D specialist, 69 patents filed, Strong in embedded systems and IoT",
    insights: "Niche expertise in product engineering and digital manufacturing solutions",
    email: "info@ltts.com",
    phone: "+91 22 6776 6776",
  },
  {
    name: "Mphasis",
    domain: "mphasis.com",
    description: "Mphasis is an Indian multinational IT services and consulting company headquartered in Bangalore. It provides infrastructure technology and application outsourcing services, with a strong focus on cloud and cognitive services.",
    founded: "2000",
    employeeRange: "10001+",
    headquarters: "Bangalore, India",
    revenueRange: "$500M - $1B",
    engagementScore: 97,
    tags: "IT Services, Cloud, Cognitive, Banking, Insurance",
    highlights: "Front2Back transformation approach, DeepInsights AI platform, BFSI domain leadership",
    insights: "Strong direct-core strategy, growing hyper-personalization and cloud-native services",
    email: "info@mphasis.com",
    phone: "+91 80 4004 0404",
  },
  {
    name: "LTIMindtree",
    domain: "ltimindtree.com",
    description: "LTIMindtree is an Indian multinational IT services and consulting company formed by the merger of Larsen & Toubro Infotech and Mindtree. It offers technology consulting, digital solutions, and enterprise services.",
    founded: "2022",
    employeeRange: "10001+",
    headquarters: "Mumbai, India",
    revenueRange: "$1B+",
    engagementScore: 97,
    tags: "IT Services, Digital, Cloud, Data Analytics, AI",
    highlights: "Merged entity of LTI and Mindtree, Canvas.ai platform, Strong in data and analytics",
    insights: "Combined scale with deep digital expertise, accelerating cloud transformation engagements",
    email: "info@ltimindtree.com",
    phone: "+91 22 6105 5000",
  },
  {
    name: "Persistent Systems",
    domain: "persistent.com",
    description: "Persistent Systems is an Indian multinational technology services company headquartered in Pune. It specializes in software product development, digital transformation, and enterprise modernization.",
    founded: "1990",
    employeeRange: "10001+",
    headquarters: "Pune, India",
    revenueRange: "$500M - $1B",
    engagementScore: 96,
    tags: "Software Engineering, Digital, Cloud, Healthcare IT",
    highlights: "Product engineering DNA, Strong ISV partnerships, Healthcare and life sciences focus",
    insights: "Differentiated product engineering heritage, growing SaaS and platform play",
    email: "info@persistent.com",
    phone: "+91 20 6703 0000",
  },
  {
    name: "Cyient",
    domain: "cyient.com",
    description: "Cyient (formerly Infotech Enterprises) is a global engineering and technology solutions company headquartered in Hyderabad. It provides geospatial, engineering, IT, and DLM solutions to various industries.",
    founded: "1991",
    employeeRange: "10001+",
    headquarters: "Hyderabad, India",
    revenueRange: "$500M - $1B",
    engagementScore: 96,
    tags: "Engineering Services, Geospatial, DLM, Aerospace, Defense",
    highlights: "Geospatial and engineering leader, Aerospace and defense expertise, Design-led manufacturing",
    insights: "Unique combination of digital engineering and geospatial intelligence capabilities",
    email: "info@cyient.com",
    phone: "+91 40 6764 1000",
  },
  {
    name: "NIIT Technologies",
    domain: "coforgetech.com",
    description: "NIIT Technologies (now Coforge) is an Indian IT services company providing digital services in travel, insurance, and banking. Rebranded as Coforge, it focuses on enterprise-grade digital transformation.",
    founded: "1992",
    employeeRange: "5001-10000",
    headquarters: "Greater Noida, India",
    revenueRange: "$500M - $1B",
    engagementScore: 96,
    tags: "IT Services, Travel, Insurance, Banking, Digital",
    highlights: "Travel and transport vertical dominance, Coforge rebrand, Insurance BPS market leader",
    insights: "Deep domain expertise in travel-transport and insurance, accelerating digital revenue",
    email: "info@coforgetech.com",
    phone: "+91 120 408 0000",
  },
  {
    name: "Zensar Technologies",
    domain: "zensar.com",
    description: "Zensar Technologies is an Indian multinational IT services company headquartered in Pune. A part of the RPG Group, it provides digital solutions, application services, and technology infrastructure services.",
    founded: "1991",
    employeeRange: "5001-10000",
    headquarters: "Pune, India",
    revenueRange: "$100M - $500M",
    engagementScore: 96,
    tags: "IT Services, Digital, Experience, RPG Group",
    highlights: "Experience-led digital transformation, Part of RPG Group, Strong in retail and manufacturing",
    insights: "Growing experience-first consulting approach, strong client mining strategy",
    email: "info@zensar.com",
    phone: "+91 20 2704 0000",
  },
  {
    name: "Hexaware Technologies",
    domain: "hexaware.com",
    description: "Hexaware Technologies is an Indian IT services and BPS company headquartered in Mumbai. It focuses on automation-led next-generation services including cloud, data, AI, and digital assurance.",
    founded: "1990",
    employeeRange: "10001+",
    headquarters: "Mumbai, India",
    revenueRange: "$500M - $1B",
    engagementScore: 96,
    tags: "IT Services, Automation, Cloud, BPS, Digital Assurance",
    highlights: "Automation-led services, Tensai AI platform, Cloud smartshore delivery model",
    insights: "Automation-first DNA with strong BPS integration, growing cloud-native services",
    email: "info@hexaware.com",
    phone: "+91 22 6191 4000",
  },
  {
    name: "Birlasoft",
    domain: "birlasoft.com",
    description: "Birlasoft is an Indian IT services company and part of the CK Birla Group. It provides enterprise digital and IT services across multiple industries including manufacturing, BFSI, and life sciences.",
    founded: "1990",
    employeeRange: "5001-10000",
    headquarters: "Noida, India",
    revenueRange: "$100M - $500M",
    engagementScore: 95,
    tags: "IT Services, Enterprise, SAP, Oracle, CK Birla Group",
    highlights: "CK Birla Group company, Strong SAP and Oracle practice, Manufacturing vertical depth",
    insights: "Deep ERP and enterprise application expertise, growing digital practice",
    email: "info@birlasoft.com",
    phone: "+91 120 662 6000",
  },
  {
    name: "Coforge",
    domain: "coforge.com",
    description: "Coforge Limited (formerly NIIT Technologies) is a global IT solutions company providing digital services to customers across multiple industries including banking, insurance, travel, and transportation.",
    founded: "1992",
    employeeRange: "10001+",
    headquarters: "Greater Noida, India",
    revenueRange: "$500M - $1B",
    engagementScore: 95,
    tags: "IT Services, Digital, BPS, Insurance, Travel",
    highlights: "Insurance and travel domain leader, BPS excellence, Acquisition-led growth strategy",
    insights: "Strong domain-led digital transformation approach, expanding geographical footprint",
    email: "info@coforge.com",
    phone: "+91 120 408 0000",
  },
  {
    name: "Sonata Software",
    domain: "sonata-software.com",
    description: "Sonata Software is an Indian multinational IT services company headquartered in Bangalore. It provides IT consulting, product engineering, and digital transformation services with a platform-centric approach.",
    founded: "1989",
    employeeRange: "5001-10000",
    headquarters: "Bangalore, India",
    revenueRange: "$100M - $500M",
    engagementScore: 95,
    tags: "IT Services, Platforms, Digital, Microsoft, Dynamics",
    highlights: "Platformation strategy, Microsoft Gold Partner, Strong Dynamics 365 practice",
    insights: "Platform-centric approach differentiator, strong Microsoft ecosystem partnership",
    email: "info@sonata-software.com",
    phone: "+91 80 6778 1999",
  },
  {
    name: "KPIT Technologies",
    domain: "kpit.com",
    description: "KPIT Technologies is a global technology company headquartered in Pune specializing in automotive software integration and connected, autonomous, shared, and electric (CASE) vehicle technologies.",
    founded: "1990",
    employeeRange: "5001-10000",
    headquarters: "Pune, India",
    revenueRange: "$100M - $500M",
    engagementScore: 95,
    tags: "Automotive Tech, CASE, Embedded Software, ADAS, EV",
    highlights: "Automotive software leader, CASE mobility expertise, ADAS and EV solutions",
    insights: "Unique automotive technology focus, benefiting from global EV and autonomous driving wave",
    email: "info@kpit.com",
    phone: "+91 20 6770 5000",
  },
  {
    name: "Tata Elxsi",
    domain: "tataelxsi.com",
    description: "Tata Elxsi is an Indian design and technology company, part of the Tata Group. It specializes in product design, automotive, broadcast, communications, and healthcare engineering services.",
    founded: "1989",
    employeeRange: "5001-10000",
    headquarters: "Bangalore, India",
    revenueRange: "$100M - $500M",
    engagementScore: 95,
    tags: "Design, Engineering, Automotive, Media, Healthcare, Tata Group",
    highlights: "Design-led innovation, Tata Group company, AUTONOMAI autonomous driving platform",
    insights: "Intersection of design and engineering, strong in media and communications verticals",
    email: "info@tataelxsi.com",
    phone: "+91 80 2297 9123",
  },
  {
    name: "Sasken Technologies",
    domain: "sasken.com",
    description: "Sasken Technologies is an Indian product engineering and digital transformation company headquartered in Bangalore. It provides chip-to-cognition digital transformation services for semiconductor and automotive industries.",
    founded: "1989",
    employeeRange: "1001-5000",
    headquarters: "Bangalore, India",
    revenueRange: "$50M - $100M",
    engagementScore: 95,
    tags: "Product Engineering, Semiconductor, Automotive, IoT, Digital",
    highlights: "Chip-to-cognition expertise, Semiconductor and automotive focus, IoT solutions",
    insights: "Niche expertise in embedded product engineering, benefiting from IoT and connected device growth",
    email: "info@sasken.com",
    phone: "+91 80 6694 3000",
  },
  {
    name: "Mascon Global",
    domain: "masconglobal.com",
    description: "Mascon Global is an Indian IT services company providing technology solutions, staff augmentation, and managed services to clients across North America and India.",
    founded: "1988",
    employeeRange: "1001-5000",
    headquarters: "Chennai, India",
    revenueRange: "$10M - $25M",
    engagementScore: 95,
    tags: "IT Services, Staff Augmentation, Managed Services",
    highlights: "Strong US presence, Staff augmentation expertise, Managed IT services focus",
    insights: "Steady growth in managed services, expanding digital transformation capabilities",
    email: "info@masconglobal.com",
    phone: "+91 44 4202 8000",
  },
  {
    name: "eClerx Services",
    domain: "eclerx.com",
    description: "eClerx Services is an Indian knowledge process outsourcing company headquartered in Mumbai. It provides data analytics, process management, and automation solutions to global enterprises in financial services and digital sectors.",
    founded: "2000",
    employeeRange: "5001-10000",
    headquarters: "Mumbai, India",
    revenueRange: "$100M - $500M",
    engagementScore: 95,
    tags: "KPO, Data Analytics, Financial Services, Digital Operations",
    highlights: "Financial services KPO leader, Digital analytics expertise, Process automation solutions",
    insights: "Strong data-driven operations expertise, growing digital transformation advisory",
    email: "info@eclerx.com",
    phone: "+91 22 6114 2000",
  },
  {
    name: "Firstsource Solutions",
    domain: "firstsource.com",
    description: "Firstsource Solutions is an Indian BPM company, a subsidiary of RP-Sanjiv Goenka Group. It provides customized business process management services to clients in banking, healthcare, and telecom sectors.",
    founded: "2001",
    employeeRange: "10001+",
    headquarters: "Mumbai, India",
    revenueRange: "$500M - $1B",
    engagementScore: 95,
    tags: "BPM, Banking, Healthcare, Telecom, RP-SG Group",
    highlights: "RP-Sanjiv Goenka Group company, Healthcare and banking BPM leader, Digital-first approach",
    insights: "Domain-specific BPM excellence, growing digital-first operations model",
    email: "info@firstsource.com",
    phone: "+91 22 6666 0888",
  },
  {
    name: "Happiest Minds Technologies",
    domain: "happiestminds.com",
    description: "Happiest Minds Technologies is an Indian digital transformation and IT services company headquartered in Bangalore. Founded by Ashok Soota, it focuses on born-digital capabilities across infrastructure, security, and IoT.",
    founded: "2011",
    employeeRange: "5001-10000",
    headquarters: "Bangalore, India",
    revenueRange: "$100M - $500M",
    engagementScore: 95,
    tags: "Digital Transformation, IoT, Security, Cloud Native",
    highlights: "Born-digital IT company, Mindful IT Company positioning, IoT and security focus",
    insights: "Digital-native DNA with strong security and IoT capabilities, growing cloud practice",
    email: "info@happiestminds.com",
    phone: "+91 80 6176 4000",
  },
  {
    name: "Rolta India",
    domain: "rolta.com",
    description: "Rolta India Limited is an Indian multinational company providing IT solutions for defense, security, geospatial, and engineering design. It offers enterprise-grade technology solutions to government and corporate sectors.",
    founded: "1989",
    employeeRange: "1001-5000",
    headquarters: "Mumbai, India",
    revenueRange: "$100M - $500M",
    engagementScore: 95,
    tags: "Defense IT, Geospatial, Engineering Design, GIS, Enterprise",
    highlights: "Defense and geospatial expertise, Government sector solutions, Engineering design leader",
    insights: "Strong in defense and government IT, unique geospatial and GIS capabilities",
    email: "info@rolta.com",
    phone: "+91 22 2926 6666",
  },
  {
    name: "Polaris Consulting & Services",
    domain: "polarisft.com",
    description: "Polaris Consulting (now Virtusa Polaris) is an Indian IT solutions company focused on financial technology and banking. It provides comprehensive financial technology products and services to global financial institutions.",
    founded: "1993",
    employeeRange: "5001-10000",
    headquarters: "Chennai, India",
    revenueRange: "$100M - $500M",
    engagementScore: 95,
    tags: "Fintech, Banking Technology, Financial Services, Product Engineering",
    highlights: "Financial technology leader, Intellect Design Arena spinoff, Banking product expertise",
    insights: "Deep fintech domain expertise, pioneer in banking product engineering",
    email: "info@polarisft.com",
    phone: "+91 44 4292 5000",
  },
  {
    name: "Nucleus Software Exports",
    domain: "nucleussoftware.com",
    description: "Nucleus Software is an Indian IT company providing lending and transaction banking solutions to the global financial services industry. Its FinnOne Neo platform is used by over 200 financial institutions worldwide.",
    founded: "1986",
    employeeRange: "1001-5000",
    headquarters: "New Delhi, India",
    revenueRange: "$50M - $100M",
    engagementScore: 95,
    tags: "Fintech, Lending, Banking Software, FinnOne",
    highlights: "FinnOne Neo lending platform, 200+ global clients, Lending automation pioneer",
    insights: "Dominant lending technology platform, growing digital lending and analytics features",
    email: "info@nucleussoftware.com",
    phone: "+91 11 4625 5000",
  },
  {
    name: "Quick Heal Technologies",
    domain: "quickheal.com",
    description: "Quick Heal Technologies (now Seqrite) is an Indian cybersecurity company headquartered in Pune. It provides security solutions including antivirus, endpoint security, and enterprise cybersecurity products.",
    founded: "1993",
    employeeRange: "1001-5000",
    headquarters: "Pune, India",
    revenueRange: "$50M - $100M",
    engagementScore: 95,
    tags: "Cybersecurity, Antivirus, Endpoint Security, Seqrite",
    highlights: "India's leading cybersecurity brand, Seqrite enterprise security, GoDeep.AI malware analysis",
    insights: "Growing enterprise security business under Seqrite brand, expanding cloud security portfolio",
    email: "info@quickheal.com",
    phone: "+91 20 6681 3232",
  },
  {
    name: "Muthoot Systems Technologies",
    domain: "muthoottechnologies.com",
    description: "Muthoot Systems Technologies is an IT services arm of the Muthoot Pappachan Group providing technology solutions, digital transformation, and IT consulting services across financial and business sectors.",
    founded: "2002",
    employeeRange: "501-1000",
    headquarters: "Kochi, India",
    revenueRange: "$10M - $25M",
    engagementScore: 95,
    tags: "IT Services, Financial Tech, Digital, Muthoot Group",
    highlights: "Muthoot Pappachan Group company, Financial services technology, Digital transformation",
    insights: "Growing digital transformation arm of a major financial conglomerate",
    email: "info@muthoottechnologies.com",
    phone: "+91 484 235 9999",
  },
  {
    name: "Intellect Design Arena",
    domain: "intellectdesign.com",
    description: "Intellect Design Arena is an Indian financial technology company providing a comprehensive suite of banking and insurance products. Its iGTB, iGCB, and Intellect AI platforms serve 250+ customers across 97 countries.",
    founded: "2011",
    employeeRange: "5001-10000",
    headquarters: "Chennai, India",
    revenueRange: "$100M - $500M",
    engagementScore: 95,
    tags: "Fintech, Banking Platform, Insurance Tech, AI, Digital Core Banking",
    highlights: "iGTB transaction banking platform, Global banking product leader, 250+ clients in 97 countries",
    insights: "Comprehensive banking product suite, strong AI-powered financial platform strategy",
    email: "info@intellectdesign.com",
    phone: "+91 44 4292 5800",
  },
  {
    name: "Newgen Software Technologies",
    domain: "newgensoft.com",
    description: "Newgen Software is an Indian IT company providing a unified digital transformation platform including low-code development, process automation, content management, and AI/ML capabilities.",
    founded: "1992",
    employeeRange: "1001-5000",
    headquarters: "New Delhi, India",
    revenueRange: "$100M - $500M",
    engagementScore: 95,
    tags: "Low-Code, Process Automation, Content Management, BPM, AI/ML",
    highlights: "Low-code platform leader, OmniDocs content management, NewgenONE platform",
    insights: "Strong low-code automation platform, growing AI/ML integration across product suite",
    email: "info@newgensoft.com",
    phone: "+91 11 4077 0100",
  },
];

// ── 25 International IT Companies ───────────────────────────────────
const internationalITCompanies = [
  {
    name: "Accenture",
    domain: "accenture.com",
    description: "Accenture is a global professional services company providing strategy, consulting, digital, technology, and operations services. One of the largest consulting firms in the world.",
    founded: "1989",
    employeeRange: "10001+",
    headquarters: "Dublin, Ireland",
    region: "Europe",
    revenueRange: "$1B+",
    engagementScore: 94,
    tags: "Consulting, Technology, Digital, Strategy, Operations",
    highlights: "Fortune Global 500, World's largest consulting firm, Digital transformation leader",
    insights: "Global scale with deep industry expertise, leading the cloud and AI transformation wave",
  },
  {
    name: "IBM",
    domain: "ibm.com",
    description: "International Business Machines Corporation (IBM) is an American multinational technology company. It operates in cloud computing, AI (Watson), quantum computing, and enterprise software.",
    founded: "1911",
    employeeRange: "10001+",
    headquarters: "Armonk, New York, USA",
    region: "Americas",
    revenueRange: "$1B+",
    engagementScore: 93,
    tags: "Cloud, AI, Quantum Computing, Enterprise Software, Hybrid Cloud",
    highlights: "Watson AI platform, Red Hat acquisition, Quantum computing leadership",
    insights: "Pivoting to hybrid cloud and AI, strong enterprise middleware position",
  },
  {
    name: "Microsoft",
    domain: "microsoft.com",
    description: "Microsoft Corporation is an American multinational technology corporation. It produces computer software, consumer electronics, personal computers, and services including Azure cloud, Office 365, and LinkedIn.",
    founded: "1975",
    employeeRange: "10001+",
    headquarters: "Redmond, Washington, USA",
    region: "Americas",
    revenueRange: "$1B+",
    engagementScore: 93,
    tags: "Cloud, Software, Azure, AI, Productivity, Enterprise",
    highlights: "Azure cloud platform, Microsoft 365, GitHub acquisition, OpenAI partnership",
    insights: "Dominant enterprise cloud position, AI integration across product portfolio via Copilot",
  },
  {
    name: "SAP",
    domain: "sap.com",
    description: "SAP SE is a German multinational software company that develops enterprise application software to manage business operations and customer relations. It is the world's largest ERP provider.",
    founded: "1972",
    employeeRange: "10001+",
    headquarters: "Walldorf, Germany",
    region: "Europe",
    revenueRange: "$1B+",
    engagementScore: 92,
    tags: "ERP, Enterprise Software, Cloud, S/4HANA, Business Intelligence",
    highlights: "World's largest ERP provider, S/4HANA cloud migration wave, Business AI innovations",
    insights: "Massive enterprise installed base migrating to cloud, strong industry-specific solutions",
  },
  {
    name: "Oracle",
    domain: "oracle.com",
    description: "Oracle Corporation is an American multinational computer technology corporation. It specializes in database management systems, cloud engineering, and enterprise resource planning software.",
    founded: "1977",
    employeeRange: "10001+",
    headquarters: "Austin, Texas, USA",
    region: "Americas",
    revenueRange: "$1B+",
    engagementScore: 92,
    tags: "Database, Cloud, ERP, SaaS, Enterprise Software",
    highlights: "Oracle Cloud Infrastructure, Autonomous Database, Cerner healthcare acquisition",
    insights: "Aggressive cloud infrastructure growth, strong autonomous database differentiation",
  },
  {
    name: "Capgemini",
    domain: "capgemini.com",
    description: "Capgemini SE is a French multinational IT services and consulting company. It provides consulting, technology, professional, and outsourcing services with a strong presence in Europe and globally.",
    founded: "1967",
    employeeRange: "10001+",
    headquarters: "Paris, France",
    region: "Europe",
    revenueRange: "$1B+",
    engagementScore: 91,
    tags: "IT Services, Consulting, Cloud, Digital, Outsourcing",
    highlights: "European IT services leader, Altran acquisition, Intelligent Industry expertise",
    insights: "Strong European market position, growing intelligent industry and sustainability practice",
  },
  {
    name: "Cognizant",
    domain: "cognizant.com",
    description: "Cognizant is an American multinational IT services and consulting company. Originally a subsidiary of Dun & Bradstreet, it provides digital, technology, consulting, and operations services globally.",
    founded: "1994",
    employeeRange: "10001+",
    headquarters: "Teaneck, New Jersey, USA",
    region: "Americas",
    revenueRange: "$1B+",
    engagementScore: 91,
    tags: "IT Services, Digital, Consulting, Cloud, Healthcare IT",
    highlights: "Healthcare and life sciences expertise, Digital engineering growth, Triple horizon strategy",
    insights: "Transforming to a digital-first model, strong healthcare and financial services verticals",
  },
  {
    name: "Deloitte",
    domain: "deloitte.com",
    description: "Deloitte Touche Tohmatsu Limited is a multinational professional services network. Its technology consulting arm provides digital transformation, AI, cloud, and cybersecurity solutions to enterprises worldwide.",
    founded: "1845",
    employeeRange: "10001+",
    headquarters: "London, United Kingdom",
    region: "Europe",
    revenueRange: "$1B+",
    engagementScore: 90,
    tags: "Consulting, Technology, Advisory, Audit, Tax",
    highlights: "Big Four firm, Technology consulting leader, AI and analytics pioneer",
    insights: "Technology-forward consulting approach, strong government and public sector practice",
  },
  {
    name: "DXC Technology",
    domain: "dxc.com",
    description: "DXC Technology is an American multinational IT services company formed by the merger of CSC and HP Enterprise Services. It provides IT outsourcing, consulting, and cloud services to enterprises globally.",
    founded: "2017",
    employeeRange: "10001+",
    headquarters: "Ashburn, Virginia, USA",
    region: "Americas",
    revenueRange: "$1B+",
    engagementScore: 90,
    tags: "IT Outsourcing, Cloud, Enterprise, Consulting, Managed Services",
    highlights: "CSC and HPE merger, Global IT outsourcing leader, Cloud modernization focus",
    insights: "Large-scale IT outsourcing to cloud transformation pivot, government sector strength",
  },
  {
    name: "Atos",
    domain: "atos.net",
    description: "Atos SE is a French multinational IT services company. It provides cloud services, cybersecurity, high-performance computing, and digital workplace solutions across Europe and globally.",
    founded: "1997",
    employeeRange: "10001+",
    headquarters: "Bezons, France",
    region: "Europe",
    revenueRange: "$1B+",
    engagementScore: 89,
    tags: "IT Services, Cloud, Cybersecurity, HPC, Digital Workplace",
    highlights: "Olympic IT services provider, BDS cybersecurity spinoff, High-performance computing leader",
    insights: "Restructuring into focused tech entities, strong cybersecurity and sovereign cloud capabilities",
  },
  {
    name: "NTT Data",
    domain: "nttdata.com",
    description: "NTT DATA is a Japanese multinational IT services and consulting company, a subsidiary of Nippon Telegraph and Telephone. It provides consulting, system integration, and managed services globally.",
    founded: "1988",
    employeeRange: "10001+",
    headquarters: "Tokyo, Japan",
    region: "Asia-Pacific",
    revenueRange: "$1B+",
    engagementScore: 89,
    tags: "IT Services, Consulting, System Integration, Managed Services, NTT Group",
    highlights: "NTT Group company, Global system integration leader, Strong in Japanese and European markets",
    insights: "Expanding global footprint through acquisitions, strong data center and network capabilities",
  },
  {
    name: "Fujitsu",
    domain: "fujitsu.com",
    description: "Fujitsu Limited is a Japanese multinational IT equipment and services company. It provides technology products, solutions, and services across computing, networking, and digital transformation.",
    founded: "1935",
    employeeRange: "10001+",
    headquarters: "Tokyo, Japan",
    region: "Asia-Pacific",
    revenueRange: "$1B+",
    engagementScore: 88,
    tags: "IT Infrastructure, Services, Quantum Computing, Supercomputing, Digital",
    highlights: "Fugaku supercomputer, Quantum computing research, Japanese market leader",
    insights: "Transitioning from hardware to services-led model, strong in quantum and HPC research",
  },
  {
    name: "CGI Group",
    domain: "cgi.com",
    description: "CGI Group is a Canadian multinational IT consulting and services company. It provides end-to-end IT and business consulting, systems integration, and managed services to government and enterprise clients.",
    founded: "1976",
    employeeRange: "10001+",
    headquarters: "Montreal, Canada",
    region: "Americas",
    revenueRange: "$1B+",
    engagementScore: 88,
    tags: "IT Consulting, Systems Integration, Managed Services, Government, IP Solutions",
    highlights: "Strong government sector presence, IP-based solutions portfolio, Canadian market leader",
    insights: "Balanced portfolio of managed services and IP solutions, strong government relationships",
  },
  {
    name: "Unisys",
    domain: "unisys.com",
    description: "Unisys Corporation is an American multinational IT company providing digital workplace services, cloud infrastructure, enterprise computing, and cybersecurity solutions to commercial and government clients.",
    founded: "1986",
    employeeRange: "10001+",
    headquarters: "Blue Bell, Pennsylvania, USA",
    region: "Americas",
    revenueRange: "$1B+",
    engagementScore: 87,
    tags: "IT Services, Cloud, Cybersecurity, Digital Workplace, Government",
    highlights: "ClearPath Forward mainframe platform, Stealth cybersecurity solution, Government sector focus",
    insights: "Transitioning to next-gen IT services, strong cybersecurity and government capabilities",
  },
  {
    name: "Sopra Steria",
    domain: "soprasteria.com",
    description: "Sopra Steria is a French multinational IT services company providing consulting, digital services, and software development. It is one of the major European IT consulting firms with strong public sector expertise.",
    founded: "1968",
    employeeRange: "10001+",
    headquarters: "Paris, France",
    region: "Europe",
    revenueRange: "$1B+",
    engagementScore: 87,
    tags: "IT Consulting, Digital Services, Software, Public Sector, Banking",
    highlights: "European IT leader, Strong public sector practice, Banking software expertise",
    insights: "Strong European public sector and banking presence, growing digital transformation revenue",
  },
  {
    name: "Kyndryl",
    domain: "kyndryl.com",
    description: "Kyndryl is the world's largest IT infrastructure services provider, spun off from IBM. It designs, builds, manages, and modernizes the complex, mission-critical information systems that enterprises depend on.",
    founded: "2021",
    employeeRange: "10001+",
    headquarters: "New York, USA",
    region: "Americas",
    revenueRange: "$1B+",
    engagementScore: 86,
    tags: "IT Infrastructure, Managed Services, Cloud, Mainframe, Modernization",
    highlights: "IBM spinoff, World's largest IT infrastructure provider, Mission-critical systems expertise",
    insights: "Transforming from traditional infrastructure management to modern hybrid cloud services",
  },
  {
    name: "Globant",
    domain: "globant.com",
    description: "Globant is an Argentine-born digitally native technology services company. It provides innovative digital and cognitive transformation services, combining engineering, design, and innovation at scale.",
    founded: "2003",
    employeeRange: "10001+",
    headquarters: "Buenos Aires, Argentina",
    region: "Americas",
    revenueRange: "$1B+",
    engagementScore: 86,
    tags: "Digital Transformation, AI, Design, Engineering, Innovation",
    highlights: "Digitally native company, Studio model delivery, Disney and Google client relationships",
    insights: "Born-digital DNA with creative studio approach, strong in AI and user experience innovation",
  },
  {
    name: "EPAM Systems",
    domain: "epam.com",
    description: "EPAM Systems is a global digital platform engineering and software development company headquartered in Pennsylvania. It provides digital engineering, intelligent enterprise, and product design services.",
    founded: "1993",
    employeeRange: "10001+",
    headquarters: "Newtown, Pennsylvania, USA",
    region: "Americas",
    revenueRange: "$1B+",
    engagementScore: 86,
    tags: "Digital Engineering, Software Development, Cloud, Data, AI",
    highlights: "Digital engineering specialist, Strong Eastern European talent pool, Product development DNA",
    insights: "Premium digital engineering positioning, expanding AI and data capabilities",
  },
  {
    name: "Endava",
    domain: "endava.com",
    description: "Endava is a British multinational technology company providing digital transformation, agile transformation, and automation services. It combines technology with creative design and engineering.",
    founded: "2000",
    employeeRange: "5001-10000",
    headquarters: "London, United Kingdom",
    region: "Europe",
    revenueRange: "$500M - $1B",
    engagementScore: 85,
    tags: "Digital Transformation, Agile, Engineering, Payments, Financial Services",
    highlights: "Payments technology expertise, European engineering excellence, High-growth trajectory",
    insights: "Strong payments and financial services niche, European nearshore delivery advantage",
  },
  {
    name: "Thoughtworks",
    domain: "thoughtworks.com",
    description: "Thoughtworks is a global technology consultancy that integrates strategy, design, and software engineering to enable enterprises to build innovative products and modernize legacy systems.",
    founded: "1993",
    employeeRange: "5001-10000",
    headquarters: "Chicago, USA",
    region: "Americas",
    revenueRange: "$500M - $1B",
    engagementScore: 85,
    tags: "Technology Consulting, Software Engineering, Agile, Open Source, DevOps",
    highlights: "Agile and open-source pioneer, Technology Radar publication, Martin Fowler association",
    insights: "Thought leadership in software engineering practices, strong developer community brand",
  },
  {
    name: "Softserve",
    domain: "softserveinc.com",
    description: "SoftServe is a Ukrainian-founded IT consulting and digital services company. It provides software engineering, cloud, big data, and IoT solutions to enterprises in healthcare, retail, and financial services.",
    founded: "1993",
    employeeRange: "5001-10000",
    headquarters: "Austin, Texas, USA",
    region: "Americas",
    revenueRange: "$500M - $1B",
    engagementScore: 84,
    tags: "Software Engineering, Cloud, Big Data, IoT, Healthcare IT",
    highlights: "Ukrainian engineering heritage, Healthcare and retail verticals, Cloud-native expertise",
    insights: "Strong Eastern European engineering talent, growing healthcare and cloud practices",
  },
  {
    name: "Luxoft",
    domain: "luxoft.com",
    description: "Luxoft is a global digital strategy and engineering company, a subsidiary of DXC Technology. It provides bespoke technology solutions in automotive, financial services, and healthcare.",
    founded: "2000",
    employeeRange: "5001-10000",
    headquarters: "Zug, Switzerland",
    region: "Europe",
    revenueRange: "$500M - $1B",
    engagementScore: 84,
    tags: "Digital Engineering, Automotive, Financial Services, DXC Technology",
    highlights: "DXC subsidiary, Automotive digital cockpit expertise, Financial services technology",
    insights: "Premium digital engineering positioning, strong automotive connected car capabilities",
  },
  {
    name: "Nagarro",
    domain: "nagarro.com",
    description: "Nagarro is a German digital engineering company providing technology consulting, digital product engineering, and platform services. It operates as a 'non-hierarchical' global organization.",
    founded: "1996",
    employeeRange: "10001+",
    headquarters: "Munich, Germany",
    region: "Europe",
    revenueRange: "$500M - $1B",
    engagementScore: 84,
    tags: "Digital Engineering, Product Engineering, Cloud, AI, SAP",
    highlights: "CARING philosophy, Non-hierarchical organization, German engineering precision",
    insights: "Unique organizational model with strong engineering culture, growing AI and data practice",
  },
  {
    name: "Virtusa",
    domain: "virtusa.com",
    description: "Virtusa Corporation is a global IT services company providing digital engineering and IT outsourcing services. It focuses on digital business transformation for banking, insurance, healthcare, and telecom sectors.",
    founded: "1996",
    employeeRange: "10001+",
    headquarters: "Southborough, Massachusetts, USA",
    region: "Americas",
    revenueRange: "$500M - $1B",
    engagementScore: 83,
    tags: "IT Services, Digital Engineering, Banking, Insurance, Telecom",
    highlights: "Digital engineering leader, Banking and telecom vertical depth, Polaris integration",
    insights: "Strong banking digital transformation practice, growing open banking and API capabilities",
  },
];

async function main() {
  console.log("Fetching default workspace...");
  const workspace = await prisma.workspace.findFirst();
  if (!workspace) {
    console.error("No workspace found. Run base seed first.");
    process.exit(1);
  }
  const workspaceId = workspace.id;
  console.log(`Using workspace: ${workspace.name} (${workspaceId})`);

  // ── Upsert Indian IT MNCs ──────────────────────────────────────────
  console.log("\n── Inserting 30 Indian IT MNCs ──");
  for (const company of indianITMncs) {
    // Check if already exists by domain
    const existing = await prisma.company.findFirst({
      where: { domain: company.domain, workspaceId },
    });

    if (existing) {
      console.log(`  ✓ Already exists: ${company.name} (updating scores)`);
      await prisma.company.update({
        where: { id: existing.id },
        data: {
          engagementScore: company.engagementScore,
          description: company.description,
          highlights: company.highlights,
          insights: company.insights,
          tags: company.tags,
        },
      });
    } else {
      await prisma.company.create({
        data: {
          workspaceId,
          name: company.name,
          category: CATEGORY,
          description: company.description,
          domain: company.domain,
          website: `https://${company.domain}`,
          founded: company.founded,
          employeeRange: company.employeeRange,
          headquarters: company.headquarters,
          region: REGION_INDIA,
          revenueRange: company.revenueRange,
          engagementScore: company.engagementScore,
          trustSignals: "Verified Indian MNC, Public Listed",
          tags: company.tags,
          email: company.email ?? `info@${company.domain}`,
          phone: company.phone ?? "+91 000 000 0000",
          highlights: company.highlights,
          insights: company.insights,
        },
      });
      console.log(`  ✓ Created: ${company.name}`);
    }
  }

  // ── Upsert International IT Companies ─────────────────────────────
  console.log("\n── Inserting 25 International IT Companies ──");
  for (const company of internationalITCompanies) {
    const existing = await prisma.company.findFirst({
      where: { domain: company.domain, workspaceId },
    });

    if (existing) {
      console.log(`  ✓ Already exists: ${company.name} (updating scores)`);
      await prisma.company.update({
        where: { id: existing.id },
        data: {
          engagementScore: company.engagementScore,
          description: company.description,
          highlights: company.highlights,
          insights: company.insights,
          tags: company.tags,
        },
      });
    } else {
      await prisma.company.create({
        data: {
          workspaceId,
          name: company.name,
          category: CATEGORY,
          description: company.description,
          domain: company.domain,
          website: `https://${company.domain}`,
          founded: company.founded,
          employeeRange: company.employeeRange,
          headquarters: company.headquarters,
          region: company.region,
          revenueRange: company.revenueRange,
          engagementScore: company.engagementScore,
          trustSignals: "Verified Global Enterprise",
          tags: company.tags,
          email: `info@${company.domain}`,
          phone: "+1 800 000 0000",
          highlights: company.highlights,
          insights: company.insights,
        },
      });
      console.log(`  ✓ Created: ${company.name}`);
    }
  }

  // ── Summary ─────────────────────────────────────────────────────────
  const indianCount = await prisma.company.count({
    where: {
      category: CATEGORY,
      headquarters: { contains: "India" },
      engagementScore: { gte: 95 },
    },
  });

  const totalIT = await prisma.company.count({
    where: { category: CATEGORY },
  });

  console.log(`\n── Summary ──`);
  console.log(`Indian IT MNCs (score >= 95): ${indianCount}`);
  console.log(`Total IT & Services companies: ${totalIT}`);
  console.log("Done! Indian MNCs will appear first when filtering IT & Services.");
}

main()
  .catch((e) => {
    console.error("Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
