export const COMPANY_EMPLOYEE_RANGES = [
  "1-10",
  "11-20",
  "21-50",
  "51-100",
  "101-200",
  "51-200",
  "201-500",
  "501-1000",
  "1001-2000",
  "2001-5000",
  "1001-5000",
  "5001-10000",
  "10001+",
  "1001+",
] as const;

// Full alphabetical country list (195 = UN member states + observer states),
// matching worldometers.info/geography/alphabetical-list-of-countries.
//
// NOTE: this is the full picker list, not the set of countries actually present
// in the discovery dataset. `headquarters` values currently only cover a handful
// of countries (USA, UK, Germany, France, India, Japan, Singapore, Australia,
// Canada), so most entries here return no results until the dataset is
// broadened. app/api/companies/route.ts maps the display names that differ from
// the stored values (e.g. "United States of America" -> "USA").
export const COMPANY_COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Côte d'Ivoire",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia (Czech Republic)",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Holy See",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (formerly Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const;

export const COMPANY_LOCATION_REGIONS = [
  "Americas",
  "Europe",
  "Africa & Middle East",
  "Asia-Pacific",
] as const;

export const COMPANY_CATEGORIES = [
  "information technology & services",
  "construction",
  "marketing and advertising",
  "real estate",
  "health, wellness & fitness",
  "management consulting",
  "computer software",
  "internet",
  "retail",
  "financial services",
  "consumer services",
  "hospital & health care",
  "automotive",
  "restaurants",
  "education management",
  "agriculture",
  "design",
  "hospitality",
  "accounting",
  "trade show events",
] as const;

export type CompanyRegion = (typeof COMPANY_LOCATION_REGIONS)[number];

const REGION_ALIASES: Record<CompanyRegion, readonly string[]> = {
  "Asia-Pacific": [
    "Australia",
    "Bangladesh",
    "Bangalore",
    "Bengaluru",
    "Beijing",
    "Cambodia",
    "Chennai",
    "China",
    "Colombo",
    "Hong Kong",
    "Hyderabad",
    "India",
    "Indonesia",
    "Islamabad",
    "Japan",
    "Karachi",
    "Korea",
    "Lahore",
    "Malaysia",
    "Melbourne",
    "Mumbai",
    "Myanmar",
    "Nepal",
    "New Delhi",
    "New Zealand",
    "Pakistan",
    "Philippines",
    "Shanghai",
    "Singapore",
    "South Korea",
    "Sri Lanka",
    "Sydney",
    "Taiwan",
    "Thailand",
    "Tokyo",
    "Vietnam",
  ],
  "Africa & Middle East": [
    "Abu Dhabi",
    "Bahrain",
    "Cairo",
    "Doha",
    "Dubai",
    "Egypt",
    "Israel",
    "Jeddah",
    "Johannesburg",
    "Jordan",
    "Kenya",
    "Kuwait",
    "Morocco",
    "Nigeria",
    "Oman",
    "Qatar",
    "Riyadh",
    "Saudi Arabia",
    "South Africa",
    "Turkey",
    "U A E",
    "UAE",
    "United Arab Emirates",
  ],
  Europe: [
    "Amsterdam",
    "Berlin",
    "Denmark",
    "England",
    "France",
    "Germany",
    "Ireland",
    "Italy",
    "London",
    "Netherlands",
    "Norway",
    "Poland",
    "Portugal",
    "Spain",
    "Sweden",
    "Switzerland",
    "U K",
    "UK",
    "United Kingdom",
  ],
  Americas: [
    "Austin",
    "Boston",
    "Brazil",
    "Canada",
    "Chicago",
    "Dallas",
    "Denver",
    "Los Angeles",
    "Mexico",
    "Miami",
    "New York",
    "San Diego",
    "Seattle",
    "Toronto",
    "U S A",
    "USA",
    "United States",
  ],
};

function normalizeLocation(value: string) {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function locationContainsAlias(normalizedLocation: string, alias: string) {
  const normalizedAlias = normalizeLocation(alias);

  if (!normalizedAlias) {
    return false;
  }

  return ` ${normalizedLocation} `.includes(` ${normalizedAlias} `);
}

export function inferCompanyRegion(headquarters: string | null | undefined): CompanyRegion | null {
  const normalizedLocation = normalizeLocation(headquarters ?? "");

  if (!normalizedLocation) {
    return null;
  }

  for (const region of COMPANY_LOCATION_REGIONS) {
    if (REGION_ALIASES[region].some((alias) => locationContainsAlias(normalizedLocation, alias))) {
      return region;
    }
  }

  return null;
}
