-- Gives public.profiles a sequential numeric primary key.
--
--     BEFORE                           AFTER
--     id      uuid PK -> auth.users     id      bigint PK IDENTITY (1,2,3...)
--                                       user_id uuid UNIQUE -> auth.users
--
-- ⚠️ PARTIAL MIGRATION. The two triggers on auth.users (on_auth_user_created,
-- on_auth_user_email_updated) must be re-pointed at the rewritten function
-- bodies as part of this change, and they live in the `auth` schema, which
-- Prisma 5 cannot manage without the multiSchema preview feature. The complete,
-- idempotent change -- including those triggers and the full rationale -- is in:
--     supabase/sql/006_profile_numeric_id.sql
-- Apply that file FIRST when bootstrapping a new environment, then mark this
-- migration applied rather than running it twice:
--     npx prisma migrate resolve --applied 20260909120000_profile_numeric_id
--
-- This migration covers the Prisma-owned (public schema) part only. It is kept
-- in step with 006 so `prisma migrate deploy` and the Dashboard SQL Editor
-- cannot drift.
--
-- The uuid is NOT dropped. It moves to `user_id`, keeping the foreign key to
-- auth.users(id) and its ON DELETE CASCADE, because auth.uid() returns uuid and
-- is what the RLS policies, both signup triggers and every /api/profile lookup
-- match against. Retyping the column in place would have severed all four.
--
-- Dropping profiles_pkey is safe: no table in the database has a foreign key
-- referencing public.profiles, so nothing depends on that index.

-- The RLS policies reference the column being renamed; they are recreated
-- against user_id below.
DROP POLICY IF EXISTS "profiles_select_own" ON "public"."profiles";
DROP POLICY IF EXISTS "profiles_insert_own" ON "public"."profiles";
DROP POLICY IF EXISTS "profiles_update_own" ON "public"."profiles";

-- id -> user_id. The rename carries profiles_id_fkey with it.
ALTER TABLE "public"."profiles" RENAME COLUMN "id" TO "user_id";
ALTER TABLE "public"."profiles" RENAME CONSTRAINT "profiles_id_fkey" TO "profiles_user_id_fkey";

ALTER TABLE "public"."profiles" DROP CONSTRAINT "profiles_pkey";
ALTER TABLE "public"."profiles" ADD CONSTRAINT "profiles_user_id_key" UNIQUE ("user_id");

-- Backfilled by created_at rather than left to the identity, which would number
-- existing rows in physical (arbitrary) order.
ALTER TABLE "public"."profiles" ADD COLUMN "id" BIGINT;

UPDATE "public"."profiles" p
   SET "id" = s.seq
  FROM (
    SELECT "user_id", row_number() OVER (ORDER BY "created_at", "user_id") AS seq
      FROM "public"."profiles"
  ) s
 WHERE p."user_id" = s."user_id";

ALTER TABLE "public"."profiles" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "public"."profiles" ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."profiles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;

-- CRITICAL: the identity's sequence starts at 1, so without this the next
-- signup collides with a backfilled row. That unique violation would be raised
-- inside the signup transaction by handle_new_auth_user() and would roll back
-- the auth.users insert, breaking sign-up entirely.
DO $do$
DECLARE
  max_id BIGINT;
BEGIN
  SELECT max("id") INTO max_id FROM "public"."profiles";
  IF max_id IS NOT NULL THEN
    PERFORM setval(pg_get_serial_sequence('public.profiles', 'id'), max_id, true);
  END IF;
END
$do$;

COMMENT ON COLUMN "public"."profiles"."id" IS
  'Sequential profile number (1, 2, 3, ...). Generated by the database; never supplied by the client.';
COMMENT ON COLUMN "public"."profiles"."user_id" IS
  'The Supabase Auth user (auth.users.id). This -- not id -- is what auth.uid() matches.';

-- RLS, recreated against user_id. Same meaning as before: the uuid moved
-- column, so the comparison follows it. UPDATE keeps both USING and WITH CHECK
-- -- without WITH CHECK a user could reassign user_id and hijack a profile.
CREATE POLICY "profiles_select_own" ON "public"."profiles"
  FOR SELECT TO authenticated USING (auth.uid() = "user_id");

CREATE POLICY "profiles_insert_own" ON "public"."profiles"
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = "user_id");

CREATE POLICY "profiles_update_own" ON "public"."profiles"
  FOR UPDATE TO authenticated USING (auth.uid() = "user_id") WITH CHECK (auth.uid() = "user_id");

GRANT USAGE, SELECT ON SEQUENCE "public"."profiles_id_seq" TO authenticated;

-- The signup trigger's function. Replaced, not dropped, so the trigger on
-- auth.users keeps pointing at it and no signup lands without a profile. The
-- INSERT no longer lists `id`: omitting it is what makes the identity fire.
CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
begin
  insert into public.profiles (user_id, first_name, middle_name, last_name, email, phone)
  values (
    new.id,
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'first_name'), ''),
      split_part(coalesce(new.email, ''), '@', 1)
    ),
    nullif(trim(new.raw_user_meta_data ->> 'middle_name'), ''),
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'last_name'), ''), ''),
    coalesce(new.email, ''),
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'phone'), ''), new.phone)
  )
  on conflict (user_id) do nothing;

  return new;
end;
$fn$;

CREATE OR REPLACE FUNCTION public.sync_auth_user_email()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
begin
  if new.email is distinct from old.email and new.email is not null then
    update public.profiles set email = new.email where user_id = new.id;
  end if;

  return new;
end;
$fn$;
